#ifndef DLDL_FILETEMPLATE_LDO_LDO_MAINSOURCETEMPLATE_h
#define DLDL_FILETEMPLATE_LDO_LDO_MAINSOURCETEMPLATE_h

#include <variant>
#include <vector>
#include <string>

namespace DLDL::filetemplate::ldo::ldo
{

	/*!	\class MainSourceTemplate
	 *
	 *	\brief Generates code for "MainSourceTemplate"
	 *
	 *	\details This is generated by DST.
	 *	For more information visit: https://github.com/Deruago/DeamerStringTemplate
	 */
	class MainSourceTemplate
	{
	public:
		enum class Type
{
Unknown,
Scope,

// User defined types
comma_extension_,
comment_,
default_ctor_,
default_ldo_namespace_,
default_none_namespace_,
default_std_namespace_,
explicit_lpd_namespace_,
explicit_lpd_namespace_dispatch_,
file_,
ldo_compare_,
ldo_ctor_,
ldo_ctor_member_,
ldo_ctor_member_assignment_,
ldo_ctor_optional_,
ldo_ctor_standard_,
ldo_ctor_vector_,
ldo_default_ctor_enum_,
ldo_default_ctor_ldo_,
ldo_default_ctor_member_,
ldo_default_ctor_optional_,
ldo_default_ctor_string_,
ldo_default_ctor_struct_,
ldo_default_ctor_vector_,
ldo_member_,
ldo_member_optional_,
ldo_member_reference_,
ldo_member_standard_,
ldo_member_vector_,
ldo_name_,
ldo_namespace_,
ldo_specific_function_,
ldo_specific_include_,
left_angle_bracket_,
left_bracket_,
left_curly_bracket_,
loc_impl_,
loc_main_,
loc_tool_,
location_,
lpd_ctor_member_impl_,
lpd_default_ctor_member_impl_,
lpd_default_ctor_member_impl_default_,
lpd_name_,
member_full_type_,
member_name_,
member_type_,
optional_default_ctor_,
optional_pointer_,
right_angle_bracket_,
right_bracket_,
right_curly_bracket_,


};


		enum class ScopeType
{
Unknown,

// Default
Default_,
Upper_,
Lower_,

Snake_,
Slash_,
BackSlash_,
Colon_,
DoubleColon_,

Variable_Field_,
Variable_Field_Separator_,
Function_Field_,
Function_Field_Separator_,


};


		static constexpr const char* ConvertEnumToName(::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type enumerationValue)
{
	switch(enumerationValue)
	{
	case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::comma_extension_:
{
	return "comma_extension";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::comment_:
{
	return "comment";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::default_ctor_:
{
	return "default_ctor";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::default_ldo_namespace_:
{
	return "default_ldo_namespace";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::default_none_namespace_:
{
	return "default_none_namespace";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::default_std_namespace_:
{
	return "default_std_namespace";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::explicit_lpd_namespace_:
{
	return "explicit_lpd_namespace";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::explicit_lpd_namespace_dispatch_:
{
	return "explicit_lpd_namespace_dispatch";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::file_:
{
	return "file";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_compare_:
{
	return "ldo_compare";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_ctor_:
{
	return "ldo_ctor";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_ctor_member_:
{
	return "ldo_ctor_member";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_ctor_member_assignment_:
{
	return "ldo_ctor_member_assignment";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_ctor_optional_:
{
	return "ldo_ctor_optional";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_ctor_standard_:
{
	return "ldo_ctor_standard";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_ctor_vector_:
{
	return "ldo_ctor_vector";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_enum_:
{
	return "ldo_default_ctor_enum";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_ldo_:
{
	return "ldo_default_ctor_ldo";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_member_:
{
	return "ldo_default_ctor_member";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_optional_:
{
	return "ldo_default_ctor_optional";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_string_:
{
	return "ldo_default_ctor_string";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_struct_:
{
	return "ldo_default_ctor_struct";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_vector_:
{
	return "ldo_default_ctor_vector";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_member_:
{
	return "ldo_member";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_member_optional_:
{
	return "ldo_member_optional";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_member_reference_:
{
	return "ldo_member_reference";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_member_standard_:
{
	return "ldo_member_standard";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_member_vector_:
{
	return "ldo_member_vector";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_name_:
{
	return "ldo_name";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_namespace_:
{
	return "ldo_namespace";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_specific_function_:
{
	return "ldo_specific_function";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_specific_include_:
{
	return "ldo_specific_include";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::left_angle_bracket_:
{
	return "left_angle_bracket";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::left_bracket_:
{
	return "left_bracket";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::left_curly_bracket_:
{
	return "left_curly_bracket";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::loc_impl_:
{
	return "loc_impl";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::loc_main_:
{
	return "loc_main";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::loc_tool_:
{
	return "loc_tool";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::location_:
{
	return "location";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::lpd_ctor_member_impl_:
{
	return "lpd_ctor_member_impl";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::lpd_default_ctor_member_impl_:
{
	return "lpd_default_ctor_member_impl";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::lpd_default_ctor_member_impl_default_:
{
	return "lpd_default_ctor_member_impl_default";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::lpd_name_:
{
	return "lpd_name";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::member_full_type_:
{
	return "member_full_type";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::member_name_:
{
	return "member_name";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::member_type_:
{
	return "member_type";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::optional_default_ctor_:
{
	return "optional_default_ctor";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::optional_pointer_:
{
	return "optional_pointer";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::right_angle_bracket_:
{
	return "right_angle_bracket";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::right_bracket_:
{
	return "right_bracket";
}

case ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::right_curly_bracket_:
{
	return "right_curly_bracket";
}


	}

	return "";
}


		
	public:
		struct VariableBase
		{
			// The value is either a string
			// or a vector of variables.
			std::variant<std::string, std::vector<VariableBase*>> value;
			bool isString = true;

			::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::Unknown;

			VariableBase() : VariableBase(std::vector<VariableBase*>())
			{
			}

			virtual ~VariableBase() = default;

			VariableBase(const char* text)
			{
				isString = true;
				value = text;
			}

			VariableBase(const std::string& text)
			{
				isString = true;
				value = text;
			}

			VariableBase(std::vector<VariableBase*> variables)
			{
				isString = false;
				value = variables;
			}

			VariableBase* This()
			{
				return this;
			}

			virtual std::string GetValue()
			{
				if (isString)
				{
					return std::get<std::string>(value);
				}
				else
				{
					std::string output;
					auto& variables = std::get<std::vector<VariableBase*>>(value);
					for (auto* variable : variables)
					{
						output += variable->GetValue();
					}
					return output;
				}
			}

			std::string GetName()
			{
				return ConvertEnumToName(type);
			}

			VariableBase& operator=(const std::string& variable)
			{
				return Set(variable);
			}

			VariableBase& operator=(VariableBase* variable)
			{
				return Set(variable);
			}

			VariableBase& operator+=(VariableBase* variable)
			{
				return Add(variable);
			}

			VariableBase& operator+=(const std::string& variable)
			{
				return Add(variable);
			}

			VariableBase& Set(const std::string& variable)
			{
				value = variable;
				isString = true;

				return *this;
			}

			VariableBase& Set(VariableBase* variable)
			{
				if (variable == this)
				{
					return *this;
				}

				value = variable->value;
				isString = variable->isString;

				return *this;
			}

			VariableBase& Add(const std::string& variable)
			{
				if (isString)
				{
					auto& text = std::get<std::string>(value);
					text += variable;
					value = text;
				}
				else
				{
					auto& vector = std::get<std::vector<VariableBase*>>(value);
					vector.push_back(new VariableBase(variable));
					value = vector;
				}

				return *this;
			}

			VariableBase& Add(VariableBase* variable)
			{
				if (variable == this)
				{
					return *this;
				}

				if (isString)
				{
					// convert current -> variablebase
					// then create a vector.
					auto& currentValue = std::get<std::string>(value);
					auto* currentValueAsVariableBase = new VariableBase(currentValue);
					value = std::vector<VariableBase*>({ currentValueAsVariableBase, variable });

					isString = false;
				}
				else
				{
					auto& vector = std::get<std::vector<VariableBase*>>(value);
					vector.push_back(variable);
					value = vector;
				}

				return *this;
			}

			void Clear()
			{
				if (isString)
				{
					value = "";
				}
				else
				{
					value = std::vector<VariableBase*>();
				}
			}

			void* operator new(size_t size)
			{
				void* newVariable = ::operator new(size);
				variables_to_delete.emplace_back(static_cast<VariableBase*>(newVariable));

				return newVariable;
			}
		};

		static VariableBase* GenerateVariable(VariableBase* variable)
		{
			return variable;
		}

		
		static VariableBase* GenerateVariable(const std::string& variable)
		{
			return new VariableBase(variable);
		}

		struct VariableScope : public VariableBase
		{
			::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::ScopeType scope_type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::ScopeType::Unknown;
			bool isReserved = false;

			VariableScope(::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::ScopeType scope_type_, bool isReserved_ = false) : VariableBase(), scope_type(scope_type_), isReserved(isReserved_)
			{
				type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::Scope;
			}

			VariableScope(const char* text, ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::ScopeType scope_type_, bool isReserved_ = false) : VariableBase(text), scope_type(scope_type_), isReserved(isReserved_)
			{
				type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::Scope;
			}

			VariableScope(std::vector<VariableBase*> variable, ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::ScopeType scope_type_, bool isReserved_ = false) : VariableBase(variable), scope_type(scope_type_), isReserved(isReserved_)
			{
				type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::Scope;
			}
		};
		
		struct Variable_ReservedScope_Upper : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Upper(VariableBase* base_)
			: VariableScope(::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::ScopeType::Upper_, true),
			  base(base_)
			{
			}
			
			virtual std::string GetValue() override
			{
				std::string upperVariant;
				std::string currentValue = base->GetValue();

				for (const auto character : currentValue)
				{
					upperVariant += std::toupper(character);
				}

				return upperVariant;
			}
		};
		
		struct Variable_ReservedScope_Lower : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Lower(VariableBase* base_)
			: VariableScope(::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::ScopeType::Lower_, true),
			  base(base_)
			{
			}
			
			virtual std::string GetValue() override
			{
				std::string lowerVariant;
				std::string currentValue = base->GetValue();

				for (const auto character : currentValue)
				{
					lowerVariant += std::tolower(character);
				}

				return lowerVariant;
			}
		};
		
		struct Variable_ReservedScope_Snake : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Snake(VariableBase* base_)
			: VariableScope(::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::ScopeType::Snake_, true),
			  base(base_)
			{
			}
			
			virtual std::string GetValue() override
			{
				std::string snakeVariant;
				std::string currentValue = base->GetValue();
				
				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						snakeVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}
						
						snakeVariant += '_';
						lastWasNonAlpha = true;
					}
				}
				
				// If it contains text
				// remove the tail
				if (!snakeVariant.empty() && lastWasNonAlpha)
				{
					snakeVariant.pop_back();
				}

				return snakeVariant;
			}
		};
		
		struct Variable_ReservedScope_Slash : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Slash(VariableBase* base_)
			: VariableScope(::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::ScopeType::Slash_, true),
			  base(base_)
			{
			}
			
			virtual std::string GetValue() override
			{
				std::string slashVariant;
				std::string currentValue = base->GetValue();
				
				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						slashVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}
						
						slashVariant += '/';
						lastWasNonAlpha = true;
					}
				}
				
				// If it contains text
				// remove the tail
				if (!slashVariant.empty() && lastWasNonAlpha)
				{
					slashVariant.pop_back();
				}

				return slashVariant;
			}
		};
		
		struct Variable_ReservedScope_DoubleColon : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_DoubleColon(VariableBase* base_)
			: VariableScope(::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::ScopeType::DoubleColon_, true),
			  base(base_)
			{
			}
			
			virtual std::string GetValue() override
			{
				std::string doubleColonVariant;
				std::string currentValue = base->GetValue();
				
				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						doubleColonVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}
						
						doubleColonVariant += "::";
						lastWasNonAlpha = true;
					}
				}
				
				// If it contains text
				// remove the tail
				if (!doubleColonVariant.empty() && lastWasNonAlpha)
				{
					doubleColonVariant.pop_back();
					doubleColonVariant.pop_back();
				}

				return doubleColonVariant;
			}
		};

		struct VariableScopes : public VariableBase
		{
			// Default scopes
			VariableBase* default_ = new VariableScope(::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::ScopeType::Default_, true);
			VariableBase* upper_ = new Variable_ReservedScope_Upper(this);
			VariableBase* lower_ = new Variable_ReservedScope_Lower(this);
			
			VariableBase* snake_ = new Variable_ReservedScope_Snake(this);
			VariableBase* slash_ = new Variable_ReservedScope_Slash(this);
			VariableBase* double_colon_ = new Variable_ReservedScope_DoubleColon(this);
			
			VariableBase* variable_field_ = new VariableScope(::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::ScopeType::Variable_Field_, true);
			VariableBase* variable_field_separator_ = new VariableScope("\n", ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::ScopeType::Variable_Field_Separator_, true);

			// Ctor
			VariableScopes() : VariableBase() {}

			VariableScopes(const char* text) : VariableBase(text) {}

			VariableScopes(const std::string& text) : VariableBase(text) {}

			VariableScopes(std::vector<VariableBase*> variables) : VariableBase(variables) {}

			// Dtor
			virtual ~VariableScopes() override = default;

			// Calls
			VariableBase* Default()
			{
				return default_;
			}
			VariableBase* Upper()
			{
				return upper_;
			}

			VariableBase* Lower()
			{
				return lower_;
			}

			VariableBase* Underscore()
			{
				return snake_;
			}

			VariableBase* Snake()
			{
				return snake_;
			}

			VariableBase* Slash()
			{
				return slash_;
			}

			VariableBase* DoubleColon()
			{
				return double_colon_;
			}

			VariableBase* Variable_Field()
			{
				return variable_field_;
			}

			VariableBase* Variable_Field_Separator()
			{
				return variable_field_separator_;
			}

			void ExpandVariableField()
			{
				// currentvalue + separator
				const auto currentValue = GetValue() + Variable_Field_Separator()->GetValue();
				*Variable_Field() += currentValue;
			}
		};

	public:
		
struct Variable_comma_extension_ : public VariableScopes
{

static constexpr auto name = "comma_extension_";



Variable_comma_extension_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::comma_extension_;
}

virtual ~Variable_comma_extension_() override = default;

Variable_comma_extension_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::comma_extension_;

}



Variable_comma_extension_& operator=(const Variable_comma_extension_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_comment_ : public VariableScopes
{

static constexpr auto name = "comment_";



Variable_comment_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::comment_;
}

virtual ~Variable_comment_() override = default;

Variable_comment_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::comment_;

}



Variable_comment_& operator=(const Variable_comment_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_default_ctor_ : public VariableScopes
{

static constexpr auto name = "default_ctor_";



Variable_default_ctor_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::default_ctor_;
}

virtual ~Variable_default_ctor_() override = default;

Variable_default_ctor_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::default_ctor_;

}



Variable_default_ctor_& operator=(const Variable_default_ctor_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_default_ldo_namespace_ : public VariableScopes
{

static constexpr auto name = "default_ldo_namespace_";



Variable_default_ldo_namespace_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::default_ldo_namespace_;
}

virtual ~Variable_default_ldo_namespace_() override = default;

Variable_default_ldo_namespace_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::default_ldo_namespace_;

}



Variable_default_ldo_namespace_& operator=(const Variable_default_ldo_namespace_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_default_none_namespace_ : public VariableScopes
{

static constexpr auto name = "default_none_namespace_";



Variable_default_none_namespace_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::default_none_namespace_;
}

virtual ~Variable_default_none_namespace_() override = default;

Variable_default_none_namespace_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::default_none_namespace_;

}



Variable_default_none_namespace_& operator=(const Variable_default_none_namespace_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_default_std_namespace_ : public VariableScopes
{

static constexpr auto name = "default_std_namespace_";



Variable_default_std_namespace_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::default_std_namespace_;
}

virtual ~Variable_default_std_namespace_() override = default;

Variable_default_std_namespace_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::default_std_namespace_;

}



Variable_default_std_namespace_& operator=(const Variable_default_std_namespace_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_explicit_lpd_namespace_ : public VariableScopes
{

static constexpr auto name = "explicit_lpd_namespace_";



Variable_explicit_lpd_namespace_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::explicit_lpd_namespace_;
}

virtual ~Variable_explicit_lpd_namespace_() override = default;

Variable_explicit_lpd_namespace_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::explicit_lpd_namespace_;

}



Variable_explicit_lpd_namespace_& operator=(const Variable_explicit_lpd_namespace_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_explicit_lpd_namespace_dispatch_ : public VariableScopes
{

static constexpr auto name = "explicit_lpd_namespace_dispatch_";



Variable_explicit_lpd_namespace_dispatch_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::explicit_lpd_namespace_dispatch_;
}

virtual ~Variable_explicit_lpd_namespace_dispatch_() override = default;

Variable_explicit_lpd_namespace_dispatch_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::explicit_lpd_namespace_dispatch_;

}



Variable_explicit_lpd_namespace_dispatch_& operator=(const Variable_explicit_lpd_namespace_dispatch_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_file_ : public VariableScopes
{

static constexpr auto name = "file_";

VariableBase* Content_ = GenerateVariable("");
VariableBase* Class_postfix_ = GenerateVariable("");
VariableBase* Extension_ = GenerateVariable("");
VariableBase* File_name_ = GenerateVariable("");
VariableBase* Namespace_ = GenerateVariable("");
VariableBase* Target_language_ = GenerateVariable("");


Variable_file_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::file_;
}

virtual ~Variable_file_() override = default;

Variable_file_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::file_;
*static_cast<VariableBase*>(Content_) = VariableBase(std::vector<VariableBase*>({ GenerateVariable("/*\n * This program is free software; you can redistribute it and/or\n * modify it under the terms of the GNU General Public License\n * as published by the Free Software Foundation; either version 3\n * of the License, or (at your option) any later version"), GenerateVariable("."), GenerateVariable("\n *\n * This program is distributed in the hope that it will be useful,\n * but WITHOUT ANY WARRANTY; without even the implied warranty of\n * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE"), GenerateVariable("."), GenerateVariable("  See the\n * GNU General Public License for more details"), GenerateVariable("."), GenerateVariable("\n *\n * You should have received a copy of the GNU General Public License\n * along with this program; if not, write to the Free Software Foundation,\n * Inc"), GenerateVariable("."), GenerateVariable(", 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA"), GenerateVariable("."), GenerateVariable("\n */\n/*\n * Part of the DeamerProject"), GenerateVariable("."), GenerateVariable("\n * For more information go to: https://github"), GenerateVariable("."), GenerateVariable("com/Deruago/theDeamerProject\n */\n\n#include \"Deamer/Language/Type/Definition/Object/"), GenerateVariable(mainsourcetemplate_->loc_impl_->This()), GenerateVariable("/"), GenerateVariable(mainsourcetemplate_->lpd_name_->This()), GenerateVariable("/"), GenerateVariable(mainsourcetemplate_->ldo_name_->This()), GenerateVariable("."), GenerateVariable("h\"\n"), GenerateVariable(mainsourcetemplate_->ldo_specific_include_->This()), GenerateVariable("\n#include <utility>\n\ndeamer::language::type::definition::object::"), GenerateVariable(mainsourcetemplate_->location_->This()), GenerateVariable(mainsourcetemplate_->explicit_lpd_namespace_->This()), GenerateVariable("::"), GenerateVariable(mainsourcetemplate_->ldo_name_->This()), GenerateVariable("::"), GenerateVariable(mainsourcetemplate_->ldo_name_->This()), GenerateVariable("("), GenerateVariable(mainsourcetemplate_->ldo_ctor_member_->Variable_Field()), GenerateVariable(")\n\t: Base(Type::"), GenerateVariable(mainsourcetemplate_->ldo_name_->This()), GenerateVariable(")"), GenerateVariable(mainsourcetemplate_->ldo_ctor_member_assignment_->Variable_Field()), GenerateVariable("\n"), GenerateVariable("{"), GenerateVariable("\n"), GenerateVariable(mainsourcetemplate_->ldo_member_reference_->Variable_Field()), GenerateVariable("\n"), GenerateVariable("}"), GenerateVariable("\n\nbool deamer::language::type::definition::object::"), GenerateVariable(mainsourcetemplate_->location_->This()), GenerateVariable(mainsourcetemplate_->explicit_lpd_namespace_->This()), GenerateVariable("::"), GenerateVariable(mainsourcetemplate_->ldo_name_->This()), GenerateVariable("::operator==(const "), GenerateVariable(mainsourcetemplate_->ldo_name_->This()), GenerateVariable("& rhs) const noexcept\n"), GenerateVariable("{"), GenerateVariable("\n\treturn this == &rhs || ("), GenerateVariable(mainsourcetemplate_->ldo_compare_->Variable_Field()), GenerateVariable("true);\n"), GenerateVariable("}"), GenerateVariable("\n\n"), GenerateVariable(mainsourcetemplate_->optional_default_ctor_->This()), GenerateVariable("\n\n"), GenerateVariable(mainsourcetemplate_->ldo_specific_function_->Variable_Field()) }));
Content_->type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::Scope;

*static_cast<VariableBase*>(Class_postfix_) = VariableBase(std::vector<VariableBase*>({  }));
Class_postfix_->type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::Scope;

*static_cast<VariableBase*>(Extension_) = VariableBase(std::vector<VariableBase*>({ GenerateVariable("h") }));
Extension_->type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::Scope;

*static_cast<VariableBase*>(File_name_) = VariableBase(std::vector<VariableBase*>({ GenerateVariable("MainSource") }));
File_name_->type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::Scope;

*static_cast<VariableBase*>(Namespace_) = VariableBase(std::vector<VariableBase*>({ GenerateVariable("DLDL::filetemplate::ldo::ldo") }));
Namespace_->type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::Scope;

*static_cast<VariableBase*>(Target_language_) = VariableBase(std::vector<VariableBase*>({ GenerateVariable("C++") }));
Target_language_->type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::Scope;


}


VariableBase* Content() const
{
	return Content_;
}

VariableBase* Class_postfix() const
{
	return Class_postfix_;
}

VariableBase* Extension() const
{
	return Extension_;
}

VariableBase* File_name() const
{
	return File_name_;
}

VariableBase* Namespace() const
{
	return Namespace_;
}

VariableBase* Target_language() const
{
	return Target_language_;
}


Variable_file_& operator=(const Variable_file_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	*Content_ = *variable.Content_;
*Class_postfix_ = *variable.Class_postfix_;
*Extension_ = *variable.Extension_;
*File_name_ = *variable.File_name_;
*Namespace_ = *variable.Namespace_;
*Target_language_ = *variable.Target_language_;


	return *this;
}

};

struct Variable_ldo_compare_ : public VariableScopes
{

static constexpr auto name = "ldo_compare_";



Variable_ldo_compare_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_compare_;
}

virtual ~Variable_ldo_compare_() override = default;

Variable_ldo_compare_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_compare_;

}



Variable_ldo_compare_& operator=(const Variable_ldo_compare_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_ctor_ : public VariableScopes
{

static constexpr auto name = "ldo_ctor_";



Variable_ldo_ctor_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_ctor_;
}

virtual ~Variable_ldo_ctor_() override = default;

Variable_ldo_ctor_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_ctor_;

}



Variable_ldo_ctor_& operator=(const Variable_ldo_ctor_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_ctor_member_ : public VariableScopes
{

static constexpr auto name = "ldo_ctor_member_";



Variable_ldo_ctor_member_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_ctor_member_;
}

virtual ~Variable_ldo_ctor_member_() override = default;

Variable_ldo_ctor_member_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_ctor_member_;

}



Variable_ldo_ctor_member_& operator=(const Variable_ldo_ctor_member_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_ctor_member_assignment_ : public VariableScopes
{

static constexpr auto name = "ldo_ctor_member_assignment_";



Variable_ldo_ctor_member_assignment_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_ctor_member_assignment_;
}

virtual ~Variable_ldo_ctor_member_assignment_() override = default;

Variable_ldo_ctor_member_assignment_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_ctor_member_assignment_;

}



Variable_ldo_ctor_member_assignment_& operator=(const Variable_ldo_ctor_member_assignment_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_ctor_optional_ : public VariableScopes
{

static constexpr auto name = "ldo_ctor_optional_";



Variable_ldo_ctor_optional_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_ctor_optional_;
}

virtual ~Variable_ldo_ctor_optional_() override = default;

Variable_ldo_ctor_optional_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_ctor_optional_;

}



Variable_ldo_ctor_optional_& operator=(const Variable_ldo_ctor_optional_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_ctor_standard_ : public VariableScopes
{

static constexpr auto name = "ldo_ctor_standard_";



Variable_ldo_ctor_standard_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_ctor_standard_;
}

virtual ~Variable_ldo_ctor_standard_() override = default;

Variable_ldo_ctor_standard_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_ctor_standard_;

}



Variable_ldo_ctor_standard_& operator=(const Variable_ldo_ctor_standard_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_ctor_vector_ : public VariableScopes
{

static constexpr auto name = "ldo_ctor_vector_";



Variable_ldo_ctor_vector_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_ctor_vector_;
}

virtual ~Variable_ldo_ctor_vector_() override = default;

Variable_ldo_ctor_vector_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_ctor_vector_;

}



Variable_ldo_ctor_vector_& operator=(const Variable_ldo_ctor_vector_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_default_ctor_enum_ : public VariableScopes
{

static constexpr auto name = "ldo_default_ctor_enum_";



Variable_ldo_default_ctor_enum_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_enum_;
}

virtual ~Variable_ldo_default_ctor_enum_() override = default;

Variable_ldo_default_ctor_enum_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_enum_;

}



Variable_ldo_default_ctor_enum_& operator=(const Variable_ldo_default_ctor_enum_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_default_ctor_ldo_ : public VariableScopes
{

static constexpr auto name = "ldo_default_ctor_ldo_";



Variable_ldo_default_ctor_ldo_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_ldo_;
}

virtual ~Variable_ldo_default_ctor_ldo_() override = default;

Variable_ldo_default_ctor_ldo_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_ldo_;

}



Variable_ldo_default_ctor_ldo_& operator=(const Variable_ldo_default_ctor_ldo_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_default_ctor_member_ : public VariableScopes
{

static constexpr auto name = "ldo_default_ctor_member_";



Variable_ldo_default_ctor_member_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_member_;
}

virtual ~Variable_ldo_default_ctor_member_() override = default;

Variable_ldo_default_ctor_member_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_member_;

}



Variable_ldo_default_ctor_member_& operator=(const Variable_ldo_default_ctor_member_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_default_ctor_optional_ : public VariableScopes
{

static constexpr auto name = "ldo_default_ctor_optional_";



Variable_ldo_default_ctor_optional_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_optional_;
}

virtual ~Variable_ldo_default_ctor_optional_() override = default;

Variable_ldo_default_ctor_optional_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_optional_;

}



Variable_ldo_default_ctor_optional_& operator=(const Variable_ldo_default_ctor_optional_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_default_ctor_string_ : public VariableScopes
{

static constexpr auto name = "ldo_default_ctor_string_";



Variable_ldo_default_ctor_string_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_string_;
}

virtual ~Variable_ldo_default_ctor_string_() override = default;

Variable_ldo_default_ctor_string_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_string_;

}



Variable_ldo_default_ctor_string_& operator=(const Variable_ldo_default_ctor_string_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_default_ctor_struct_ : public VariableScopes
{

static constexpr auto name = "ldo_default_ctor_struct_";



Variable_ldo_default_ctor_struct_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_struct_;
}

virtual ~Variable_ldo_default_ctor_struct_() override = default;

Variable_ldo_default_ctor_struct_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_struct_;

}



Variable_ldo_default_ctor_struct_& operator=(const Variable_ldo_default_ctor_struct_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_default_ctor_vector_ : public VariableScopes
{

static constexpr auto name = "ldo_default_ctor_vector_";



Variable_ldo_default_ctor_vector_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_vector_;
}

virtual ~Variable_ldo_default_ctor_vector_() override = default;

Variable_ldo_default_ctor_vector_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_default_ctor_vector_;

}



Variable_ldo_default_ctor_vector_& operator=(const Variable_ldo_default_ctor_vector_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_member_ : public VariableScopes
{

static constexpr auto name = "ldo_member_";



Variable_ldo_member_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_member_;
}

virtual ~Variable_ldo_member_() override = default;

Variable_ldo_member_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_member_;

}



Variable_ldo_member_& operator=(const Variable_ldo_member_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_member_optional_ : public VariableScopes
{

static constexpr auto name = "ldo_member_optional_";



Variable_ldo_member_optional_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_member_optional_;
}

virtual ~Variable_ldo_member_optional_() override = default;

Variable_ldo_member_optional_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_member_optional_;

}



Variable_ldo_member_optional_& operator=(const Variable_ldo_member_optional_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_member_reference_ : public VariableScopes
{

static constexpr auto name = "ldo_member_reference_";



Variable_ldo_member_reference_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_member_reference_;
}

virtual ~Variable_ldo_member_reference_() override = default;

Variable_ldo_member_reference_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_member_reference_;

}



Variable_ldo_member_reference_& operator=(const Variable_ldo_member_reference_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_member_standard_ : public VariableScopes
{

static constexpr auto name = "ldo_member_standard_";



Variable_ldo_member_standard_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_member_standard_;
}

virtual ~Variable_ldo_member_standard_() override = default;

Variable_ldo_member_standard_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_member_standard_;

}



Variable_ldo_member_standard_& operator=(const Variable_ldo_member_standard_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_member_vector_ : public VariableScopes
{

static constexpr auto name = "ldo_member_vector_";



Variable_ldo_member_vector_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_member_vector_;
}

virtual ~Variable_ldo_member_vector_() override = default;

Variable_ldo_member_vector_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_member_vector_;

}



Variable_ldo_member_vector_& operator=(const Variable_ldo_member_vector_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_name_ : public VariableScopes
{

static constexpr auto name = "ldo_name_";



Variable_ldo_name_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_name_;
}

virtual ~Variable_ldo_name_() override = default;

Variable_ldo_name_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_name_;

}



Variable_ldo_name_& operator=(const Variable_ldo_name_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_namespace_ : public VariableScopes
{

static constexpr auto name = "ldo_namespace_";



Variable_ldo_namespace_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_namespace_;
}

virtual ~Variable_ldo_namespace_() override = default;

Variable_ldo_namespace_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_namespace_;

}



Variable_ldo_namespace_& operator=(const Variable_ldo_namespace_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_specific_function_ : public VariableScopes
{

static constexpr auto name = "ldo_specific_function_";



Variable_ldo_specific_function_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_specific_function_;
}

virtual ~Variable_ldo_specific_function_() override = default;

Variable_ldo_specific_function_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_specific_function_;

}



Variable_ldo_specific_function_& operator=(const Variable_ldo_specific_function_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_specific_include_ : public VariableScopes
{

static constexpr auto name = "ldo_specific_include_";



Variable_ldo_specific_include_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_specific_include_;
}

virtual ~Variable_ldo_specific_include_() override = default;

Variable_ldo_specific_include_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::ldo_specific_include_;

}



Variable_ldo_specific_include_& operator=(const Variable_ldo_specific_include_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_left_angle_bracket_ : public VariableScopes
{

static constexpr auto name = "left_angle_bracket_";



Variable_left_angle_bracket_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::left_angle_bracket_;
}

virtual ~Variable_left_angle_bracket_() override = default;

Variable_left_angle_bracket_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::left_angle_bracket_;

}



Variable_left_angle_bracket_& operator=(const Variable_left_angle_bracket_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_left_bracket_ : public VariableScopes
{

static constexpr auto name = "left_bracket_";



Variable_left_bracket_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::left_bracket_;
}

virtual ~Variable_left_bracket_() override = default;

Variable_left_bracket_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::left_bracket_;

}



Variable_left_bracket_& operator=(const Variable_left_bracket_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_left_curly_bracket_ : public VariableScopes
{

static constexpr auto name = "left_curly_bracket_";



Variable_left_curly_bracket_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::left_curly_bracket_;
}

virtual ~Variable_left_curly_bracket_() override = default;

Variable_left_curly_bracket_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::left_curly_bracket_;

}



Variable_left_curly_bracket_& operator=(const Variable_left_curly_bracket_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_loc_impl_ : public VariableScopes
{

static constexpr auto name = "loc_impl_";



Variable_loc_impl_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::loc_impl_;
}

virtual ~Variable_loc_impl_() override = default;

Variable_loc_impl_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::loc_impl_;

}



Variable_loc_impl_& operator=(const Variable_loc_impl_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_loc_main_ : public VariableScopes
{

static constexpr auto name = "loc_main_";



Variable_loc_main_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::loc_main_;
}

virtual ~Variable_loc_main_() override = default;

Variable_loc_main_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::loc_main_;

}



Variable_loc_main_& operator=(const Variable_loc_main_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_loc_tool_ : public VariableScopes
{

static constexpr auto name = "loc_tool_";



Variable_loc_tool_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::loc_tool_;
}

virtual ~Variable_loc_tool_() override = default;

Variable_loc_tool_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::loc_tool_;

}



Variable_loc_tool_& operator=(const Variable_loc_tool_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_location_ : public VariableScopes
{

static constexpr auto name = "location_";



Variable_location_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::location_;
}

virtual ~Variable_location_() override = default;

Variable_location_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::location_;

}



Variable_location_& operator=(const Variable_location_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_lpd_ctor_member_impl_ : public VariableScopes
{

static constexpr auto name = "lpd_ctor_member_impl_";



Variable_lpd_ctor_member_impl_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::lpd_ctor_member_impl_;
}

virtual ~Variable_lpd_ctor_member_impl_() override = default;

Variable_lpd_ctor_member_impl_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::lpd_ctor_member_impl_;

}



Variable_lpd_ctor_member_impl_& operator=(const Variable_lpd_ctor_member_impl_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_lpd_default_ctor_member_impl_ : public VariableScopes
{

static constexpr auto name = "lpd_default_ctor_member_impl_";



Variable_lpd_default_ctor_member_impl_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::lpd_default_ctor_member_impl_;
}

virtual ~Variable_lpd_default_ctor_member_impl_() override = default;

Variable_lpd_default_ctor_member_impl_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::lpd_default_ctor_member_impl_;

}



Variable_lpd_default_ctor_member_impl_& operator=(const Variable_lpd_default_ctor_member_impl_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_lpd_default_ctor_member_impl_default_ : public VariableScopes
{

static constexpr auto name = "lpd_default_ctor_member_impl_default_";



Variable_lpd_default_ctor_member_impl_default_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::lpd_default_ctor_member_impl_default_;
}

virtual ~Variable_lpd_default_ctor_member_impl_default_() override = default;

Variable_lpd_default_ctor_member_impl_default_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::lpd_default_ctor_member_impl_default_;

}



Variable_lpd_default_ctor_member_impl_default_& operator=(const Variable_lpd_default_ctor_member_impl_default_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_lpd_name_ : public VariableScopes
{

static constexpr auto name = "lpd_name_";



Variable_lpd_name_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::lpd_name_;
}

virtual ~Variable_lpd_name_() override = default;

Variable_lpd_name_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::lpd_name_;

}



Variable_lpd_name_& operator=(const Variable_lpd_name_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_member_full_type_ : public VariableScopes
{

static constexpr auto name = "member_full_type_";



Variable_member_full_type_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::member_full_type_;
}

virtual ~Variable_member_full_type_() override = default;

Variable_member_full_type_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::member_full_type_;

}



Variable_member_full_type_& operator=(const Variable_member_full_type_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_member_name_ : public VariableScopes
{

static constexpr auto name = "member_name_";



Variable_member_name_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::member_name_;
}

virtual ~Variable_member_name_() override = default;

Variable_member_name_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::member_name_;

}



Variable_member_name_& operator=(const Variable_member_name_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_member_type_ : public VariableScopes
{

static constexpr auto name = "member_type_";



Variable_member_type_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::member_type_;
}

virtual ~Variable_member_type_() override = default;

Variable_member_type_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::member_type_;

}



Variable_member_type_& operator=(const Variable_member_type_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_optional_default_ctor_ : public VariableScopes
{

static constexpr auto name = "optional_default_ctor_";



Variable_optional_default_ctor_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::optional_default_ctor_;
}

virtual ~Variable_optional_default_ctor_() override = default;

Variable_optional_default_ctor_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::optional_default_ctor_;

}



Variable_optional_default_ctor_& operator=(const Variable_optional_default_ctor_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_optional_pointer_ : public VariableScopes
{

static constexpr auto name = "optional_pointer_";



Variable_optional_pointer_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::optional_pointer_;
}

virtual ~Variable_optional_pointer_() override = default;

Variable_optional_pointer_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::optional_pointer_;

}



Variable_optional_pointer_& operator=(const Variable_optional_pointer_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_right_angle_bracket_ : public VariableScopes
{

static constexpr auto name = "right_angle_bracket_";



Variable_right_angle_bracket_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::right_angle_bracket_;
}

virtual ~Variable_right_angle_bracket_() override = default;

Variable_right_angle_bracket_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::right_angle_bracket_;

}



Variable_right_angle_bracket_& operator=(const Variable_right_angle_bracket_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_right_bracket_ : public VariableScopes
{

static constexpr auto name = "right_bracket_";



Variable_right_bracket_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::right_bracket_;
}

virtual ~Variable_right_bracket_() override = default;

Variable_right_bracket_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::right_bracket_;

}



Variable_right_bracket_& operator=(const Variable_right_bracket_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_right_curly_bracket_ : public VariableScopes
{

static constexpr auto name = "right_curly_bracket_";



Variable_right_curly_bracket_() : VariableScopes()
{
	type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::right_curly_bracket_;
}

virtual ~Variable_right_curly_bracket_() override = default;

Variable_right_curly_bracket_(MainSourceTemplate* mainsourcetemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::ldo::ldo::MainSourceTemplate::Type::right_curly_bracket_;

}



Variable_right_curly_bracket_& operator=(const Variable_right_curly_bracket_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};


	public:
		inline static std::vector<VariableBase*> variables_to_delete = std::vector<VariableBase*>();

	public:
		std::vector<VariableBase*> variables_;

	public:
		// Members that one can directly access.
		// e.g. MainSourceTemplate.member = "auto-generated";
		Variable_comma_extension_* comma_extension_ = new Variable_comma_extension_();
Variable_comment_* comment_ = new Variable_comment_();
Variable_default_ctor_* default_ctor_ = new Variable_default_ctor_();
Variable_default_ldo_namespace_* default_ldo_namespace_ = new Variable_default_ldo_namespace_();
Variable_default_none_namespace_* default_none_namespace_ = new Variable_default_none_namespace_();
Variable_default_std_namespace_* default_std_namespace_ = new Variable_default_std_namespace_();
Variable_explicit_lpd_namespace_* explicit_lpd_namespace_ = new Variable_explicit_lpd_namespace_();
Variable_explicit_lpd_namespace_dispatch_* explicit_lpd_namespace_dispatch_ = new Variable_explicit_lpd_namespace_dispatch_();
Variable_file_* file_ = new Variable_file_();
Variable_ldo_compare_* ldo_compare_ = new Variable_ldo_compare_();
Variable_ldo_ctor_* ldo_ctor_ = new Variable_ldo_ctor_();
Variable_ldo_ctor_member_* ldo_ctor_member_ = new Variable_ldo_ctor_member_();
Variable_ldo_ctor_member_assignment_* ldo_ctor_member_assignment_ = new Variable_ldo_ctor_member_assignment_();
Variable_ldo_ctor_optional_* ldo_ctor_optional_ = new Variable_ldo_ctor_optional_();
Variable_ldo_ctor_standard_* ldo_ctor_standard_ = new Variable_ldo_ctor_standard_();
Variable_ldo_ctor_vector_* ldo_ctor_vector_ = new Variable_ldo_ctor_vector_();
Variable_ldo_default_ctor_enum_* ldo_default_ctor_enum_ = new Variable_ldo_default_ctor_enum_();
Variable_ldo_default_ctor_ldo_* ldo_default_ctor_ldo_ = new Variable_ldo_default_ctor_ldo_();
Variable_ldo_default_ctor_member_* ldo_default_ctor_member_ = new Variable_ldo_default_ctor_member_();
Variable_ldo_default_ctor_optional_* ldo_default_ctor_optional_ = new Variable_ldo_default_ctor_optional_();
Variable_ldo_default_ctor_string_* ldo_default_ctor_string_ = new Variable_ldo_default_ctor_string_();
Variable_ldo_default_ctor_struct_* ldo_default_ctor_struct_ = new Variable_ldo_default_ctor_struct_();
Variable_ldo_default_ctor_vector_* ldo_default_ctor_vector_ = new Variable_ldo_default_ctor_vector_();
Variable_ldo_member_* ldo_member_ = new Variable_ldo_member_();
Variable_ldo_member_optional_* ldo_member_optional_ = new Variable_ldo_member_optional_();
Variable_ldo_member_reference_* ldo_member_reference_ = new Variable_ldo_member_reference_();
Variable_ldo_member_standard_* ldo_member_standard_ = new Variable_ldo_member_standard_();
Variable_ldo_member_vector_* ldo_member_vector_ = new Variable_ldo_member_vector_();
Variable_ldo_name_* ldo_name_ = new Variable_ldo_name_();
Variable_ldo_namespace_* ldo_namespace_ = new Variable_ldo_namespace_();
Variable_ldo_specific_function_* ldo_specific_function_ = new Variable_ldo_specific_function_();
Variable_ldo_specific_include_* ldo_specific_include_ = new Variable_ldo_specific_include_();
Variable_left_angle_bracket_* left_angle_bracket_ = new Variable_left_angle_bracket_();
Variable_left_bracket_* left_bracket_ = new Variable_left_bracket_();
Variable_left_curly_bracket_* left_curly_bracket_ = new Variable_left_curly_bracket_();
Variable_loc_impl_* loc_impl_ = new Variable_loc_impl_();
Variable_loc_main_* loc_main_ = new Variable_loc_main_();
Variable_loc_tool_* loc_tool_ = new Variable_loc_tool_();
Variable_location_* location_ = new Variable_location_();
Variable_lpd_ctor_member_impl_* lpd_ctor_member_impl_ = new Variable_lpd_ctor_member_impl_();
Variable_lpd_default_ctor_member_impl_* lpd_default_ctor_member_impl_ = new Variable_lpd_default_ctor_member_impl_();
Variable_lpd_default_ctor_member_impl_default_* lpd_default_ctor_member_impl_default_ = new Variable_lpd_default_ctor_member_impl_default_();
Variable_lpd_name_* lpd_name_ = new Variable_lpd_name_();
Variable_member_full_type_* member_full_type_ = new Variable_member_full_type_();
Variable_member_name_* member_name_ = new Variable_member_name_();
Variable_member_type_* member_type_ = new Variable_member_type_();
Variable_optional_default_ctor_* optional_default_ctor_ = new Variable_optional_default_ctor_();
Variable_optional_pointer_* optional_pointer_ = new Variable_optional_pointer_();
Variable_right_angle_bracket_* right_angle_bracket_ = new Variable_right_angle_bracket_();
Variable_right_bracket_* right_bracket_ = new Variable_right_bracket_();
Variable_right_curly_bracket_* right_curly_bracket_ = new Variable_right_curly_bracket_();


	public:
		MainSourceTemplate()
		{
			*comma_extension_ = Variable_comma_extension_(this, std::vector<VariableBase*>({  }));
*comment_ = Variable_comment_(this, std::vector<VariableBase*>({  }));
*default_ctor_ = Variable_default_ctor_(this, std::vector<VariableBase*>({ GenerateVariable("\ndeamer::language::type::definition::object::"), GenerateVariable(location_->This()), GenerateVariable(explicit_lpd_namespace_->This()), GenerateVariable("::"), GenerateVariable(ldo_name_->This()), GenerateVariable("::"), GenerateVariable(ldo_name_->This()), GenerateVariable("() : "), GenerateVariable(ldo_name_->This()), GenerateVariable("("), GenerateVariable(ldo_default_ctor_member_->Variable_Field()), GenerateVariable(")\n"), GenerateVariable("{"), GenerateVariable("\n"), GenerateVariable("}"), GenerateVariable("\n") }));
*default_ldo_namespace_ = Variable_default_ldo_namespace_(this, std::vector<VariableBase*>({ GenerateVariable("object::"), GenerateVariable(location_->This()), GenerateVariable(explicit_lpd_namespace_->This()), GenerateVariable("::") }));
*default_none_namespace_ = Variable_default_none_namespace_(this, std::vector<VariableBase*>({  }));
*default_std_namespace_ = Variable_default_std_namespace_(this, std::vector<VariableBase*>({ GenerateVariable("std::") }));
*explicit_lpd_namespace_ = Variable_explicit_lpd_namespace_(this, std::vector<VariableBase*>({ GenerateVariable(explicit_lpd_namespace_dispatch_->This()) }));
*explicit_lpd_namespace_dispatch_ = Variable_explicit_lpd_namespace_dispatch_(this, std::vector<VariableBase*>({ GenerateVariable("::"), GenerateVariable(lpd_name_->Lower()) }));
*file_ = Variable_file_(this, std::vector<VariableBase*>({  }));
*ldo_compare_ = Variable_ldo_compare_(this, std::vector<VariableBase*>({ GenerateVariable("this->"), GenerateVariable(member_name_->This()), GenerateVariable(" == rhs"), GenerateVariable("."), GenerateVariable(member_name_->This()) }));
*ldo_ctor_ = Variable_ldo_ctor_(this, std::vector<VariableBase*>({ GenerateVariable(ldo_ctor_member_->Variable_Field()) }));
*ldo_ctor_member_ = Variable_ldo_ctor_member_(this, std::vector<VariableBase*>({ GenerateVariable(comma_extension_->This()), GenerateVariable(lpd_ctor_member_impl_->This()), GenerateVariable(" "), GenerateVariable(member_name_->This()), GenerateVariable("_") }));
*ldo_ctor_member_assignment_ = Variable_ldo_ctor_member_assignment_(this, std::vector<VariableBase*>({ GenerateVariable(",\n\t"), GenerateVariable(member_name_->This()), GenerateVariable("("), GenerateVariable(member_name_->This()), GenerateVariable("_)") }));
*ldo_ctor_optional_ = Variable_ldo_ctor_optional_(this, std::vector<VariableBase*>({ GenerateVariable("std::optional<"), GenerateVariable(member_full_type_->This()), GenerateVariable(">") }));
*ldo_ctor_standard_ = Variable_ldo_ctor_standard_(this, std::vector<VariableBase*>({ GenerateVariable(member_full_type_->This()) }));
*ldo_ctor_vector_ = Variable_ldo_ctor_vector_(this, std::vector<VariableBase*>({ GenerateVariable("std::vector<"), GenerateVariable(member_full_type_->This()), GenerateVariable(">") }));
*ldo_default_ctor_enum_ = Variable_ldo_default_ctor_enum_(this, std::vector<VariableBase*>({ GenerateVariable(lpd_ctor_member_impl_->This()), GenerateVariable("::reserved_default_enum_option") }));
*ldo_default_ctor_ldo_ = Variable_ldo_default_ctor_ldo_(this, std::vector<VariableBase*>({ GenerateVariable("nullptr") }));
*ldo_default_ctor_member_ = Variable_ldo_default_ctor_member_(this, std::vector<VariableBase*>({ GenerateVariable(comma_extension_->This()), GenerateVariable(lpd_default_ctor_member_impl_->This()) }));
*ldo_default_ctor_optional_ = Variable_ldo_default_ctor_optional_(this, std::vector<VariableBase*>({ GenerateVariable(lpd_ctor_member_impl_->This()), GenerateVariable("{"), GenerateVariable("}") }));
*ldo_default_ctor_string_ = Variable_ldo_default_ctor_string_(this, std::vector<VariableBase*>({ GenerateVariable("\"\"") }));
*ldo_default_ctor_struct_ = Variable_ldo_default_ctor_struct_(this, std::vector<VariableBase*>({ GenerateVariable(lpd_ctor_member_impl_->This()), GenerateVariable("{"), GenerateVariable("}") }));
*ldo_default_ctor_vector_ = Variable_ldo_default_ctor_vector_(this, std::vector<VariableBase*>({ GenerateVariable(lpd_ctor_member_impl_->This()), GenerateVariable("{"), GenerateVariable("}") }));
*ldo_member_ = Variable_ldo_member_(this, std::vector<VariableBase*>({  }));
*ldo_member_optional_ = Variable_ldo_member_optional_(this, std::vector<VariableBase*>({ GenerateVariable("\t\t"), GenerateVariable(comment_->Variable_Field()), GenerateVariable("std::optional<"), GenerateVariable(member_full_type_->This()), GenerateVariable("> "), GenerateVariable(member_name_->This()), GenerateVariable(";") }));
*ldo_member_reference_ = Variable_ldo_member_reference_(this, std::vector<VariableBase*>({ GenerateVariable("\treferences"), GenerateVariable("."), GenerateVariable("Add("), GenerateVariable(member_name_->This()), GenerateVariable(");") }));
*ldo_member_standard_ = Variable_ldo_member_standard_(this, std::vector<VariableBase*>({ GenerateVariable("\t\t"), GenerateVariable(comment_->Variable_Field()), GenerateVariable(member_full_type_->This()), GenerateVariable(" "), GenerateVariable(member_name_->This()), GenerateVariable(";") }));
*ldo_member_vector_ = Variable_ldo_member_vector_(this, std::vector<VariableBase*>({ GenerateVariable("\t\t"), GenerateVariable(comment_->Variable_Field()), GenerateVariable("std::vector<"), GenerateVariable(member_full_type_->This()), GenerateVariable("> "), GenerateVariable(member_name_->This()), GenerateVariable(";") }));
*ldo_name_ = Variable_ldo_name_(this, std::vector<VariableBase*>({  }));
*ldo_namespace_ = Variable_ldo_namespace_(this, std::vector<VariableBase*>({ GenerateVariable(default_ldo_namespace_->This()) }));
*ldo_specific_function_ = Variable_ldo_specific_function_(this, std::vector<VariableBase*>({  }));
*ldo_specific_include_ = Variable_ldo_specific_include_(this, std::vector<VariableBase*>({  }));
*left_angle_bracket_ = Variable_left_angle_bracket_(this, std::vector<VariableBase*>({ GenerateVariable("<") }));
*left_bracket_ = Variable_left_bracket_(this, std::vector<VariableBase*>({ GenerateVariable("{") }));
*left_curly_bracket_ = Variable_left_curly_bracket_(this, std::vector<VariableBase*>({ GenerateVariable("(") }));
*loc_impl_ = Variable_loc_impl_(this, std::vector<VariableBase*>({ GenerateVariable(loc_main_->This()) }));
*loc_main_ = Variable_loc_main_(this, std::vector<VariableBase*>({ GenerateVariable("Main") }));
*loc_tool_ = Variable_loc_tool_(this, std::vector<VariableBase*>({ GenerateVariable("Tool") }));
*location_ = Variable_location_(this, std::vector<VariableBase*>({ GenerateVariable(loc_impl_->Lower()) }));
*lpd_ctor_member_impl_ = Variable_lpd_ctor_member_impl_(this, std::vector<VariableBase*>({  }));
*lpd_default_ctor_member_impl_ = Variable_lpd_default_ctor_member_impl_(this, std::vector<VariableBase*>({ GenerateVariable(lpd_default_ctor_member_impl_default_->This()) }));
*lpd_default_ctor_member_impl_default_ = Variable_lpd_default_ctor_member_impl_default_(this, std::vector<VariableBase*>({ GenerateVariable(lpd_ctor_member_impl_->This()), GenerateVariable("{"), GenerateVariable("}") }));
*lpd_name_ = Variable_lpd_name_(this, std::vector<VariableBase*>({  }));
*member_full_type_ = Variable_member_full_type_(this, std::vector<VariableBase*>({ GenerateVariable(ldo_namespace_->This()), GenerateVariable(member_type_->This()), GenerateVariable(optional_pointer_->This()) }));
*member_name_ = Variable_member_name_(this, std::vector<VariableBase*>({  }));
*member_type_ = Variable_member_type_(this, std::vector<VariableBase*>({  }));
*optional_default_ctor_ = Variable_optional_default_ctor_(this, std::vector<VariableBase*>({ GenerateVariable(default_ctor_->This()) }));
*optional_pointer_ = Variable_optional_pointer_(this, std::vector<VariableBase*>({  }));
*right_angle_bracket_ = Variable_right_angle_bracket_(this, std::vector<VariableBase*>({ GenerateVariable(">") }));
*right_bracket_ = Variable_right_bracket_(this, std::vector<VariableBase*>({ GenerateVariable("}") }));
*right_curly_bracket_ = Variable_right_curly_bracket_(this, std::vector<VariableBase*>({ GenerateVariable(")") }));


			variables_.emplace_back(comma_extension_);
variables_.emplace_back(comment_);
variables_.emplace_back(default_ctor_);
variables_.emplace_back(default_ldo_namespace_);
variables_.emplace_back(default_none_namespace_);
variables_.emplace_back(default_std_namespace_);
variables_.emplace_back(explicit_lpd_namespace_);
variables_.emplace_back(explicit_lpd_namespace_dispatch_);
variables_.emplace_back(file_);
variables_.emplace_back(ldo_compare_);
variables_.emplace_back(ldo_ctor_);
variables_.emplace_back(ldo_ctor_member_);
variables_.emplace_back(ldo_ctor_member_assignment_);
variables_.emplace_back(ldo_ctor_optional_);
variables_.emplace_back(ldo_ctor_standard_);
variables_.emplace_back(ldo_ctor_vector_);
variables_.emplace_back(ldo_default_ctor_enum_);
variables_.emplace_back(ldo_default_ctor_ldo_);
variables_.emplace_back(ldo_default_ctor_member_);
variables_.emplace_back(ldo_default_ctor_optional_);
variables_.emplace_back(ldo_default_ctor_string_);
variables_.emplace_back(ldo_default_ctor_struct_);
variables_.emplace_back(ldo_default_ctor_vector_);
variables_.emplace_back(ldo_member_);
variables_.emplace_back(ldo_member_optional_);
variables_.emplace_back(ldo_member_reference_);
variables_.emplace_back(ldo_member_standard_);
variables_.emplace_back(ldo_member_vector_);
variables_.emplace_back(ldo_name_);
variables_.emplace_back(ldo_namespace_);
variables_.emplace_back(ldo_specific_function_);
variables_.emplace_back(ldo_specific_include_);
variables_.emplace_back(left_angle_bracket_);
variables_.emplace_back(left_bracket_);
variables_.emplace_back(left_curly_bracket_);
variables_.emplace_back(loc_impl_);
variables_.emplace_back(loc_main_);
variables_.emplace_back(loc_tool_);
variables_.emplace_back(location_);
variables_.emplace_back(lpd_ctor_member_impl_);
variables_.emplace_back(lpd_default_ctor_member_impl_);
variables_.emplace_back(lpd_default_ctor_member_impl_default_);
variables_.emplace_back(lpd_name_);
variables_.emplace_back(member_full_type_);
variables_.emplace_back(member_name_);
variables_.emplace_back(member_type_);
variables_.emplace_back(optional_default_ctor_);
variables_.emplace_back(optional_pointer_);
variables_.emplace_back(right_angle_bracket_);
variables_.emplace_back(right_bracket_);
variables_.emplace_back(right_curly_bracket_);

		}

		virtual ~MainSourceTemplate()
		{
			for(auto* variable : variables_to_delete)
			{
				delete variable;
			}

			variables_to_delete.clear();
		}

	public:
		// Default DST functions

		/*!	\fn GetOutput
		 *
		 *	\brief returns the output with the given the current state.
		 */
		std::string GetOutput()
		{
			return file_->Content()->GetValue();
		}

		/*!	\fn GetVariables
		 *
		 *	\brief Returns all top level variables known in this template.
		 */
		std::vector<VariableBase*> GetVariables()
		{
			return variables_;
		}

	public:
	};
}

#endif // DLDL_FILETEMPLATE_LDO_LDO_MAINSOURCETEMPLATE_h
