#ifndef DLDL_OOPSYNTAX_DLDL_OOPSYNTAX_H
#define DLDL_OOPSYNTAX_DLDL_OOPSYNTAX_H

// This is a generated file for the language: DLDL_OOPSYNTAX

namespace DLDL_OOPSYNTAX
{
}

#endif // DLDL_OOPSYNTAX_DLDL_OOPSYNTAX_H