#ifndef DLDL_GRAMMAR_PRODUCTION_RULE_DLDL_GRAMMAR_PRODUCTION_RULE_H
#define DLDL_GRAMMAR_PRODUCTION_RULE_DLDL_GRAMMAR_PRODUCTION_RULE_H

// This is a generated file for the language: DLDL_GRAMMAR_PRODUCTION_RULE

namespace DLDL_GRAMMAR_PRODUCTION_RULE
{
}

#endif // DLDL_GRAMMAR_PRODUCTION_RULE_DLDL_GRAMMAR_PRODUCTION_RULE_H