#ifndef DLDL_LPDSTRUCT_DLDL_LPDSTRUCT_H
#define DLDL_LPDSTRUCT_DLDL_LPDSTRUCT_H

// This is a generated file for the language: DLDL_LPDSTRUCT

namespace DLDL_LPDSTRUCT
{
}

#endif // DLDL_LPDSTRUCT_DLDL_LPDSTRUCT_H