#ifndef DLDL_GRAMMAR_PRODUCTION_RULE_AST_NODE_LEFT_PARANTHESIS_H
#define DLDL_GRAMMAR_PRODUCTION_RULE_AST_NODE_LEFT_PARANTHESIS_H

#include "DLDL_GRAMMAR_PRODUCTION_RULE/Ast/Node/DLDL_GRAMMAR_PRODUCTION_RULE.h"
#include <Deamer/External/Cpp/Ast/Node.h>

namespace DLDL_GRAMMAR_PRODUCTION_RULE { namespace ast { namespace node {

	class LEFT_PARANTHESIS : public DLDL_GRAMMAR_PRODUCTION_RULE<LEFT_PARANTHESIS>
	{
	private:
	public:
		LEFT_PARANTHESIS(deamer::external::cpp::ast::NodeInformation information_)
		: DLDL_GRAMMAR_PRODUCTION_RULE<LEFT_PARANTHESIS>(information_, {}, {})
		{
		}
	};

}}}

#endif // DLDL_GRAMMAR_PRODUCTION_RULE_AST_NODE_LEFT_PARANTHESIS_H
