#ifndef DLDL_FILETEMPLATE_LPD_LPD_MAINTEMPLATE_h
#define DLDL_FILETEMPLATE_LPD_LPD_MAINTEMPLATE_h

#include <variant>
#include <vector>
#include <string>

namespace DLDL::filetemplate::lpd::lpd
{

	/*!	\class MainTemplate
	 *
	 *	\brief Generates code for "MainTemplate"
	 *
	 *	\details This is generated by DST.
	 *	For more information visit: https://github.com/Deruago/DeamerStringTemplate
	 */
	class MainTemplate
	{
	public:
		enum class Type
{
Unknown,
Scope,

// User defined types
brief_description_,
brief_description_line_,
brief_description_line_content_,
comma_extension_,
comment_,
comment_content_,
detailed_description_,
detailed_description_line_,
detailed_description_line_content_,
explicit_lpd_namespace_,
explicit_lpd_namespace_dispatch_,
file_,
header_guard_,
ldo_full_type_,
ldo_include_,
ldo_name_,
ldo_namespace_,
ldo_type_,
left_angle_bracket_,
left_bracket_,
left_curly_bracket_,
loc_impl_,
loc_main_,
loc_tool_,
location_,
lpd_ctor_,
lpd_ctor_member_,
lpd_ctor_member_optional_,
lpd_ctor_member_standard_,
lpd_ctor_member_type_,
lpd_ctor_member_vector_,
lpd_member_,
lpd_member_getter_unique_,
lpd_member_optional_,
lpd_member_standard_,
lpd_member_vector_,
lpd_name_,
lpd_specific_function_,
lpd_specific_function_prototype_,
optional_pointer_,
pointer_,
right_angle_bracket_,
right_bracket_,
right_curly_bracket_,
target_lpd_name_,


};


		enum class ScopeType
{
Unknown,

// Default
Default_,
Upper_,
Lower_,

Snake_,
Slash_,
BackSlash_,
Colon_,
DoubleColon_,

Variable_Field_,
Variable_Field_Separator_,
Function_Field_,
Function_Field_Separator_,


};


		static constexpr const char* ConvertEnumToName(::DLDL::filetemplate::lpd::lpd::MainTemplate::Type enumerationValue)
{
	switch(enumerationValue)
	{
	case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::brief_description_:
{
	return "brief_description";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::brief_description_line_:
{
	return "brief_description_line";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::brief_description_line_content_:
{
	return "brief_description_line_content";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::comma_extension_:
{
	return "comma_extension";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::comment_:
{
	return "comment";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::comment_content_:
{
	return "comment_content";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::detailed_description_:
{
	return "detailed_description";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::detailed_description_line_:
{
	return "detailed_description_line";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::detailed_description_line_content_:
{
	return "detailed_description_line_content";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::explicit_lpd_namespace_:
{
	return "explicit_lpd_namespace";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::explicit_lpd_namespace_dispatch_:
{
	return "explicit_lpd_namespace_dispatch";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::file_:
{
	return "file";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::header_guard_:
{
	return "header_guard";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::ldo_full_type_:
{
	return "ldo_full_type";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::ldo_include_:
{
	return "ldo_include";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::ldo_name_:
{
	return "ldo_name";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::ldo_namespace_:
{
	return "ldo_namespace";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::ldo_type_:
{
	return "ldo_type";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::left_angle_bracket_:
{
	return "left_angle_bracket";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::left_bracket_:
{
	return "left_bracket";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::left_curly_bracket_:
{
	return "left_curly_bracket";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::loc_impl_:
{
	return "loc_impl";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::loc_main_:
{
	return "loc_main";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::loc_tool_:
{
	return "loc_tool";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::location_:
{
	return "location";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_ctor_:
{
	return "lpd_ctor";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_ctor_member_:
{
	return "lpd_ctor_member";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_ctor_member_optional_:
{
	return "lpd_ctor_member_optional";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_ctor_member_standard_:
{
	return "lpd_ctor_member_standard";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_ctor_member_type_:
{
	return "lpd_ctor_member_type";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_ctor_member_vector_:
{
	return "lpd_ctor_member_vector";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_member_:
{
	return "lpd_member";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_member_getter_unique_:
{
	return "lpd_member_getter_unique";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_member_optional_:
{
	return "lpd_member_optional";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_member_standard_:
{
	return "lpd_member_standard";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_member_vector_:
{
	return "lpd_member_vector";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_name_:
{
	return "lpd_name";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_specific_function_:
{
	return "lpd_specific_function";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_specific_function_prototype_:
{
	return "lpd_specific_function_prototype";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::optional_pointer_:
{
	return "optional_pointer";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::pointer_:
{
	return "pointer";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::right_angle_bracket_:
{
	return "right_angle_bracket";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::right_bracket_:
{
	return "right_bracket";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::right_curly_bracket_:
{
	return "right_curly_bracket";
}

case ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::target_lpd_name_:
{
	return "target_lpd_name";
}


	}

	return "";
}


		
	public:
		struct VariableBase
		{
			// The value is either a string
			// or a vector of variables.
			std::variant<std::string, std::vector<VariableBase*>> value;
			bool isString = true;

			::DLDL::filetemplate::lpd::lpd::MainTemplate::Type type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::Unknown;

			VariableBase() : VariableBase(std::vector<VariableBase*>())
			{
			}

			virtual ~VariableBase() = default;

			VariableBase(const char* text)
			{
				isString = true;
				value = text;
			}

			VariableBase(const std::string& text)
			{
				isString = true;
				value = text;
			}

			VariableBase(std::vector<VariableBase*> variables)
			{
				isString = false;
				value = variables;
			}

			VariableBase* This()
			{
				return this;
			}

			virtual std::string GetValue()
			{
				if (isString)
				{
					return std::get<std::string>(value);
				}
				else
				{
					std::string output;
					auto& variables = std::get<std::vector<VariableBase*>>(value);
					for (auto* variable : variables)
					{
						output += variable->GetValue();
					}
					return output;
				}
			}

			std::string GetName()
			{
				return ConvertEnumToName(type);
			}

			VariableBase& operator=(const std::string& variable)
			{
				return Set(variable);
			}

			VariableBase& operator=(VariableBase* variable)
			{
				return Set(variable);
			}

			VariableBase& operator+=(VariableBase* variable)
			{
				return Add(variable);
			}

			VariableBase& operator+=(const std::string& variable)
			{
				return Add(variable);
			}

			VariableBase& Set(const std::string& variable)
			{
				value = variable;
				isString = true;

				return *this;
			}

			VariableBase& Set(VariableBase* variable)
			{
				if (variable == this)
				{
					return *this;
				}

				value = variable->value;
				isString = variable->isString;

				return *this;
			}

			VariableBase& Add(const std::string& variable)
			{
				if (isString)
				{
					auto& text = std::get<std::string>(value);
					text += variable;
					value = text;
				}
				else
				{
					auto& vector = std::get<std::vector<VariableBase*>>(value);
					vector.push_back(new VariableBase(variable));
					value = vector;
				}

				return *this;
			}

			VariableBase& Add(VariableBase* variable)
			{
				if (variable == this)
				{
					return *this;
				}

				if (isString)
				{
					// convert current -> variablebase
					// then create a vector.
					auto& currentValue = std::get<std::string>(value);
					auto* currentValueAsVariableBase = new VariableBase(currentValue);
					value = std::vector<VariableBase*>({ currentValueAsVariableBase, variable });

					isString = false;
				}
				else
				{
					auto& vector = std::get<std::vector<VariableBase*>>(value);
					vector.push_back(variable);
					value = vector;
				}

				return *this;
			}

			void Clear()
			{
				if (isString)
				{
					value = "";
				}
				else
				{
					value = std::vector<VariableBase*>();
				}
			}

			void* operator new(size_t size)
			{
				void* newVariable = ::operator new(size);
				variables_to_delete.emplace_back(static_cast<VariableBase*>(newVariable));

				return newVariable;
			}
		};

		static VariableBase* GenerateVariable(VariableBase* variable)
		{
			return variable;
		}

		
		static VariableBase* GenerateVariable(const std::string& variable)
		{
			return new VariableBase(variable);
		}

		struct VariableScope : public VariableBase
		{
			::DLDL::filetemplate::lpd::lpd::MainTemplate::ScopeType scope_type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::ScopeType::Unknown;
			bool isReserved = false;

			VariableScope(::DLDL::filetemplate::lpd::lpd::MainTemplate::ScopeType scope_type_, bool isReserved_ = false) : VariableBase(), scope_type(scope_type_), isReserved(isReserved_)
			{
				type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::Scope;
			}

			VariableScope(const char* text, ::DLDL::filetemplate::lpd::lpd::MainTemplate::ScopeType scope_type_, bool isReserved_ = false) : VariableBase(text), scope_type(scope_type_), isReserved(isReserved_)
			{
				type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::Scope;
			}

			VariableScope(std::vector<VariableBase*> variable, ::DLDL::filetemplate::lpd::lpd::MainTemplate::ScopeType scope_type_, bool isReserved_ = false) : VariableBase(variable), scope_type(scope_type_), isReserved(isReserved_)
			{
				type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::Scope;
			}
		};
		
		struct Variable_ReservedScope_Upper : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Upper(VariableBase* base_)
			: VariableScope(::DLDL::filetemplate::lpd::lpd::MainTemplate::ScopeType::Upper_, true),
			  base(base_)
			{
			}
			
			virtual std::string GetValue() override
			{
				std::string upperVariant;
				std::string currentValue = base->GetValue();

				for (const auto character : currentValue)
				{
					upperVariant += std::toupper(character);
				}

				return upperVariant;
			}
		};
		
		struct Variable_ReservedScope_Lower : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Lower(VariableBase* base_)
			: VariableScope(::DLDL::filetemplate::lpd::lpd::MainTemplate::ScopeType::Lower_, true),
			  base(base_)
			{
			}
			
			virtual std::string GetValue() override
			{
				std::string lowerVariant;
				std::string currentValue = base->GetValue();

				for (const auto character : currentValue)
				{
					lowerVariant += std::tolower(character);
				}

				return lowerVariant;
			}
		};
		
		struct Variable_ReservedScope_Snake : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Snake(VariableBase* base_)
			: VariableScope(::DLDL::filetemplate::lpd::lpd::MainTemplate::ScopeType::Snake_, true),
			  base(base_)
			{
			}
			
			virtual std::string GetValue() override
			{
				std::string snakeVariant;
				std::string currentValue = base->GetValue();
				
				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						snakeVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}
						
						snakeVariant += '_';
						lastWasNonAlpha = true;
					}
				}
				
				// If it contains text
				// remove the tail
				if (!snakeVariant.empty() && lastWasNonAlpha)
				{
					snakeVariant.pop_back();
				}

				return snakeVariant;
			}
		};
		
		struct Variable_ReservedScope_Slash : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Slash(VariableBase* base_)
			: VariableScope(::DLDL::filetemplate::lpd::lpd::MainTemplate::ScopeType::Slash_, true),
			  base(base_)
			{
			}
			
			virtual std::string GetValue() override
			{
				std::string slashVariant;
				std::string currentValue = base->GetValue();
				
				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						slashVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}
						
						slashVariant += '/';
						lastWasNonAlpha = true;
					}
				}
				
				// If it contains text
				// remove the tail
				if (!slashVariant.empty() && lastWasNonAlpha)
				{
					slashVariant.pop_back();
				}

				return slashVariant;
			}
		};
		
		struct Variable_ReservedScope_DoubleColon : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_DoubleColon(VariableBase* base_)
			: VariableScope(::DLDL::filetemplate::lpd::lpd::MainTemplate::ScopeType::DoubleColon_, true),
			  base(base_)
			{
			}
			
			virtual std::string GetValue() override
			{
				std::string doubleColonVariant;
				std::string currentValue = base->GetValue();
				
				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						doubleColonVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}
						
						doubleColonVariant += "::";
						lastWasNonAlpha = true;
					}
				}
				
				// If it contains text
				// remove the tail
				if (!doubleColonVariant.empty() && lastWasNonAlpha)
				{
					doubleColonVariant.pop_back();
					doubleColonVariant.pop_back();
				}

				return doubleColonVariant;
			}
		};

		struct VariableScopes : public VariableBase
		{
			// Default scopes
			VariableBase* default_ = new VariableScope(::DLDL::filetemplate::lpd::lpd::MainTemplate::ScopeType::Default_, true);
			VariableBase* upper_ = new Variable_ReservedScope_Upper(this);
			VariableBase* lower_ = new Variable_ReservedScope_Lower(this);
			
			VariableBase* snake_ = new Variable_ReservedScope_Snake(this);
			VariableBase* slash_ = new Variable_ReservedScope_Slash(this);
			VariableBase* double_colon_ = new Variable_ReservedScope_DoubleColon(this);
			
			VariableBase* variable_field_ = new VariableScope(::DLDL::filetemplate::lpd::lpd::MainTemplate::ScopeType::Variable_Field_, true);
			VariableBase* variable_field_separator_ = new VariableScope("\n", ::DLDL::filetemplate::lpd::lpd::MainTemplate::ScopeType::Variable_Field_Separator_, true);

			// Ctor
			VariableScopes() : VariableBase() {}

			VariableScopes(const char* text) : VariableBase(text) {}

			VariableScopes(const std::string& text) : VariableBase(text) {}

			VariableScopes(std::vector<VariableBase*> variables) : VariableBase(variables) {}

			// Dtor
			virtual ~VariableScopes() override = default;

			// Calls
			VariableBase* Default()
			{
				return default_;
			}
			VariableBase* Upper()
			{
				return upper_;
			}

			VariableBase* Lower()
			{
				return lower_;
			}

			VariableBase* Underscore()
			{
				return snake_;
			}

			VariableBase* Snake()
			{
				return snake_;
			}

			VariableBase* Slash()
			{
				return slash_;
			}

			VariableBase* DoubleColon()
			{
				return double_colon_;
			}

			VariableBase* Variable_Field()
			{
				return variable_field_;
			}

			VariableBase* Variable_Field_Separator()
			{
				return variable_field_separator_;
			}

			void ExpandVariableField()
			{
				// currentvalue + separator
				const auto currentValue = GetValue() + Variable_Field_Separator()->GetValue();
				*Variable_Field() += currentValue;
			}
		};

	public:
		
struct Variable_brief_description_ : public VariableScopes
{

static constexpr auto name = "brief_description_";



Variable_brief_description_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::brief_description_;
}

virtual ~Variable_brief_description_() override = default;

Variable_brief_description_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::brief_description_;

}



Variable_brief_description_& operator=(const Variable_brief_description_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_brief_description_line_ : public VariableScopes
{

static constexpr auto name = "brief_description_line_";



Variable_brief_description_line_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::brief_description_line_;
}

virtual ~Variable_brief_description_line_() override = default;

Variable_brief_description_line_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::brief_description_line_;

}



Variable_brief_description_line_& operator=(const Variable_brief_description_line_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_brief_description_line_content_ : public VariableScopes
{

static constexpr auto name = "brief_description_line_content_";



Variable_brief_description_line_content_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::brief_description_line_content_;
}

virtual ~Variable_brief_description_line_content_() override = default;

Variable_brief_description_line_content_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::brief_description_line_content_;

}



Variable_brief_description_line_content_& operator=(const Variable_brief_description_line_content_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_comma_extension_ : public VariableScopes
{

static constexpr auto name = "comma_extension_";



Variable_comma_extension_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::comma_extension_;
}

virtual ~Variable_comma_extension_() override = default;

Variable_comma_extension_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::comma_extension_;

}



Variable_comma_extension_& operator=(const Variable_comma_extension_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_comment_ : public VariableScopes
{

static constexpr auto name = "comment_";



Variable_comment_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::comment_;
}

virtual ~Variable_comment_() override = default;

Variable_comment_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::comment_;

}



Variable_comment_& operator=(const Variable_comment_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_comment_content_ : public VariableScopes
{

static constexpr auto name = "comment_content_";



Variable_comment_content_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::comment_content_;
}

virtual ~Variable_comment_content_() override = default;

Variable_comment_content_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::comment_content_;

}



Variable_comment_content_& operator=(const Variable_comment_content_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_detailed_description_ : public VariableScopes
{

static constexpr auto name = "detailed_description_";



Variable_detailed_description_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::detailed_description_;
}

virtual ~Variable_detailed_description_() override = default;

Variable_detailed_description_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::detailed_description_;

}



Variable_detailed_description_& operator=(const Variable_detailed_description_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_detailed_description_line_ : public VariableScopes
{

static constexpr auto name = "detailed_description_line_";



Variable_detailed_description_line_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::detailed_description_line_;
}

virtual ~Variable_detailed_description_line_() override = default;

Variable_detailed_description_line_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::detailed_description_line_;

}



Variable_detailed_description_line_& operator=(const Variable_detailed_description_line_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_detailed_description_line_content_ : public VariableScopes
{

static constexpr auto name = "detailed_description_line_content_";



Variable_detailed_description_line_content_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::detailed_description_line_content_;
}

virtual ~Variable_detailed_description_line_content_() override = default;

Variable_detailed_description_line_content_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::detailed_description_line_content_;

}



Variable_detailed_description_line_content_& operator=(const Variable_detailed_description_line_content_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_explicit_lpd_namespace_ : public VariableScopes
{

static constexpr auto name = "explicit_lpd_namespace_";



Variable_explicit_lpd_namespace_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::explicit_lpd_namespace_;
}

virtual ~Variable_explicit_lpd_namespace_() override = default;

Variable_explicit_lpd_namespace_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::explicit_lpd_namespace_;

}



Variable_explicit_lpd_namespace_& operator=(const Variable_explicit_lpd_namespace_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_explicit_lpd_namespace_dispatch_ : public VariableScopes
{

static constexpr auto name = "explicit_lpd_namespace_dispatch_";



Variable_explicit_lpd_namespace_dispatch_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::explicit_lpd_namespace_dispatch_;
}

virtual ~Variable_explicit_lpd_namespace_dispatch_() override = default;

Variable_explicit_lpd_namespace_dispatch_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::explicit_lpd_namespace_dispatch_;

}



Variable_explicit_lpd_namespace_dispatch_& operator=(const Variable_explicit_lpd_namespace_dispatch_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_file_ : public VariableScopes
{

static constexpr auto name = "file_";

VariableBase* Content_ = GenerateVariable("");
VariableBase* Class_postfix_ = GenerateVariable("");
VariableBase* Extension_ = GenerateVariable("");
VariableBase* File_name_ = GenerateVariable("");
VariableBase* Namespace_ = GenerateVariable("");
VariableBase* Target_language_ = GenerateVariable("");


Variable_file_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::file_;
}

virtual ~Variable_file_() override = default;

Variable_file_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::file_;
*static_cast<VariableBase*>(Content_) = VariableBase(std::vector<VariableBase*>({ GenerateVariable("/*\n * This program is free software; you can redistribute it and/or\n * modify it under the terms of the GNU General Public License\n * as published by the Free Software Foundation; either version 3\n * of the License, or (at your option) any later version"), GenerateVariable("."), GenerateVariable("\n *\n * This program is distributed in the hope that it will be useful,\n * but WITHOUT ANY WARRANTY; without even the implied warranty of\n * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE"), GenerateVariable("."), GenerateVariable("  See the\n * GNU General Public License for more details"), GenerateVariable("."), GenerateVariable("\n *\n * You should have received a copy of the GNU General Public License\n * along with this program; if not, write to the Free Software Foundation,\n * Inc"), GenerateVariable("."), GenerateVariable(", 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA"), GenerateVariable("."), GenerateVariable("\n */\n/*\n * Part of the DeamerProject"), GenerateVariable("."), GenerateVariable("\n * For more information go to: https://github"), GenerateVariable("."), GenerateVariable("com/Deruago/theDeamerProject\n */\n\n#ifndef "), GenerateVariable(maintemplate_->header_guard_->This()), GenerateVariable("\n#define "), GenerateVariable(maintemplate_->header_guard_->This()), GenerateVariable("\n\n"), GenerateVariable(maintemplate_->ldo_include_->Variable_Field()), GenerateVariable("\n#include \"Deamer/Language/Type/Definition/Property/"), GenerateVariable(maintemplate_->loc_impl_->This()), GenerateVariable("/Definition"), GenerateVariable("."), GenerateVariable("h\"\n#include <vector>\n#include <optional>\n#include <string>\n\nnamespace deamer::language::type::definition::property::"), GenerateVariable(maintemplate_->location_->This()), GenerateVariable("\n"), GenerateVariable("{"), GenerateVariable("\n\t/*! "), GenerateVariable("\\"), GenerateVariable("class "), GenerateVariable(maintemplate_->lpd_name_->This()), GenerateVariable("\n\t *\n\t *\t"), GenerateVariable("\\"), GenerateVariable("brief "), GenerateVariable(maintemplate_->brief_description_->This()), GenerateVariable("\n\t *\t"), GenerateVariable("\\"), GenerateVariable("details "), GenerateVariable(maintemplate_->detailed_description_->This()), GenerateVariable("\n\t */\n\tclass "), GenerateVariable(maintemplate_->lpd_name_->This()), GenerateVariable(" final : public Definition\n\t"), GenerateVariable("{"), GenerateVariable("\n\tpublic:\n"), GenerateVariable(maintemplate_->lpd_member_->Variable_Field()), GenerateVariable("\n\t\n\tpublic:\n\t\t"), GenerateVariable(maintemplate_->lpd_name_->This()), GenerateVariable("("), GenerateVariable(maintemplate_->lpd_ctor_->This()), GenerateVariable(");\n\t\tvirtual ~"), GenerateVariable(maintemplate_->lpd_name_->This()), GenerateVariable("() = default;\n\n\tpublic:\n"), GenerateVariable(maintemplate_->lpd_specific_function_->Variable_Field()), GenerateVariable("\n\n\tpublic:\n\t\t"), GenerateVariable(maintemplate_->lpd_member_getter_unique_->Variable_Field()), GenerateVariable("\n\t"), GenerateVariable("}"), GenerateVariable(";\n"), GenerateVariable("}"), GenerateVariable("\n\n#endif // "), GenerateVariable(maintemplate_->header_guard_->This()), GenerateVariable("\n") }));
Content_->type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::Scope;

*static_cast<VariableBase*>(Class_postfix_) = VariableBase(std::vector<VariableBase*>({  }));
Class_postfix_->type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::Scope;

*static_cast<VariableBase*>(Extension_) = VariableBase(std::vector<VariableBase*>({ GenerateVariable("h") }));
Extension_->type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::Scope;

*static_cast<VariableBase*>(File_name_) = VariableBase(std::vector<VariableBase*>({ GenerateVariable("Main") }));
File_name_->type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::Scope;

*static_cast<VariableBase*>(Namespace_) = VariableBase(std::vector<VariableBase*>({ GenerateVariable("DLDL::filetemplate::lpd::lpd") }));
Namespace_->type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::Scope;

*static_cast<VariableBase*>(Target_language_) = VariableBase(std::vector<VariableBase*>({ GenerateVariable("C++") }));
Target_language_->type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::Scope;


}


VariableBase* Content() const
{
	return Content_;
}

VariableBase* Class_postfix() const
{
	return Class_postfix_;
}

VariableBase* Extension() const
{
	return Extension_;
}

VariableBase* File_name() const
{
	return File_name_;
}

VariableBase* Namespace() const
{
	return Namespace_;
}

VariableBase* Target_language() const
{
	return Target_language_;
}


Variable_file_& operator=(const Variable_file_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	*Content_ = *variable.Content_;
*Class_postfix_ = *variable.Class_postfix_;
*Extension_ = *variable.Extension_;
*File_name_ = *variable.File_name_;
*Namespace_ = *variable.Namespace_;
*Target_language_ = *variable.Target_language_;


	return *this;
}

};

struct Variable_header_guard_ : public VariableScopes
{

static constexpr auto name = "header_guard_";



Variable_header_guard_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::header_guard_;
}

virtual ~Variable_header_guard_() override = default;

Variable_header_guard_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::header_guard_;

}



Variable_header_guard_& operator=(const Variable_header_guard_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_full_type_ : public VariableScopes
{

static constexpr auto name = "ldo_full_type_";



Variable_ldo_full_type_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::ldo_full_type_;
}

virtual ~Variable_ldo_full_type_() override = default;

Variable_ldo_full_type_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::ldo_full_type_;

}



Variable_ldo_full_type_& operator=(const Variable_ldo_full_type_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_include_ : public VariableScopes
{

static constexpr auto name = "ldo_include_";



Variable_ldo_include_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::ldo_include_;
}

virtual ~Variable_ldo_include_() override = default;

Variable_ldo_include_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::ldo_include_;

}



Variable_ldo_include_& operator=(const Variable_ldo_include_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_name_ : public VariableScopes
{

static constexpr auto name = "ldo_name_";



Variable_ldo_name_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::ldo_name_;
}

virtual ~Variable_ldo_name_() override = default;

Variable_ldo_name_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::ldo_name_;

}



Variable_ldo_name_& operator=(const Variable_ldo_name_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_namespace_ : public VariableScopes
{

static constexpr auto name = "ldo_namespace_";



Variable_ldo_namespace_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::ldo_namespace_;
}

virtual ~Variable_ldo_namespace_() override = default;

Variable_ldo_namespace_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::ldo_namespace_;

}



Variable_ldo_namespace_& operator=(const Variable_ldo_namespace_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_ldo_type_ : public VariableScopes
{

static constexpr auto name = "ldo_type_";



Variable_ldo_type_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::ldo_type_;
}

virtual ~Variable_ldo_type_() override = default;

Variable_ldo_type_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::ldo_type_;

}



Variable_ldo_type_& operator=(const Variable_ldo_type_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_left_angle_bracket_ : public VariableScopes
{

static constexpr auto name = "left_angle_bracket_";



Variable_left_angle_bracket_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::left_angle_bracket_;
}

virtual ~Variable_left_angle_bracket_() override = default;

Variable_left_angle_bracket_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::left_angle_bracket_;

}



Variable_left_angle_bracket_& operator=(const Variable_left_angle_bracket_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_left_bracket_ : public VariableScopes
{

static constexpr auto name = "left_bracket_";



Variable_left_bracket_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::left_bracket_;
}

virtual ~Variable_left_bracket_() override = default;

Variable_left_bracket_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::left_bracket_;

}



Variable_left_bracket_& operator=(const Variable_left_bracket_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_left_curly_bracket_ : public VariableScopes
{

static constexpr auto name = "left_curly_bracket_";



Variable_left_curly_bracket_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::left_curly_bracket_;
}

virtual ~Variable_left_curly_bracket_() override = default;

Variable_left_curly_bracket_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::left_curly_bracket_;

}



Variable_left_curly_bracket_& operator=(const Variable_left_curly_bracket_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_loc_impl_ : public VariableScopes
{

static constexpr auto name = "loc_impl_";



Variable_loc_impl_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::loc_impl_;
}

virtual ~Variable_loc_impl_() override = default;

Variable_loc_impl_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::loc_impl_;

}



Variable_loc_impl_& operator=(const Variable_loc_impl_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_loc_main_ : public VariableScopes
{

static constexpr auto name = "loc_main_";



Variable_loc_main_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::loc_main_;
}

virtual ~Variable_loc_main_() override = default;

Variable_loc_main_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::loc_main_;

}



Variable_loc_main_& operator=(const Variable_loc_main_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_loc_tool_ : public VariableScopes
{

static constexpr auto name = "loc_tool_";



Variable_loc_tool_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::loc_tool_;
}

virtual ~Variable_loc_tool_() override = default;

Variable_loc_tool_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::loc_tool_;

}



Variable_loc_tool_& operator=(const Variable_loc_tool_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_location_ : public VariableScopes
{

static constexpr auto name = "location_";



Variable_location_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::location_;
}

virtual ~Variable_location_() override = default;

Variable_location_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::location_;

}



Variable_location_& operator=(const Variable_location_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_lpd_ctor_ : public VariableScopes
{

static constexpr auto name = "lpd_ctor_";



Variable_lpd_ctor_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_ctor_;
}

virtual ~Variable_lpd_ctor_() override = default;

Variable_lpd_ctor_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_ctor_;

}



Variable_lpd_ctor_& operator=(const Variable_lpd_ctor_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_lpd_ctor_member_ : public VariableScopes
{

static constexpr auto name = "lpd_ctor_member_";



Variable_lpd_ctor_member_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_ctor_member_;
}

virtual ~Variable_lpd_ctor_member_() override = default;

Variable_lpd_ctor_member_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_ctor_member_;

}



Variable_lpd_ctor_member_& operator=(const Variable_lpd_ctor_member_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_lpd_ctor_member_optional_ : public VariableScopes
{

static constexpr auto name = "lpd_ctor_member_optional_";



Variable_lpd_ctor_member_optional_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_ctor_member_optional_;
}

virtual ~Variable_lpd_ctor_member_optional_() override = default;

Variable_lpd_ctor_member_optional_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_ctor_member_optional_;

}



Variable_lpd_ctor_member_optional_& operator=(const Variable_lpd_ctor_member_optional_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_lpd_ctor_member_standard_ : public VariableScopes
{

static constexpr auto name = "lpd_ctor_member_standard_";



Variable_lpd_ctor_member_standard_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_ctor_member_standard_;
}

virtual ~Variable_lpd_ctor_member_standard_() override = default;

Variable_lpd_ctor_member_standard_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_ctor_member_standard_;

}



Variable_lpd_ctor_member_standard_& operator=(const Variable_lpd_ctor_member_standard_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_lpd_ctor_member_type_ : public VariableScopes
{

static constexpr auto name = "lpd_ctor_member_type_";



Variable_lpd_ctor_member_type_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_ctor_member_type_;
}

virtual ~Variable_lpd_ctor_member_type_() override = default;

Variable_lpd_ctor_member_type_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_ctor_member_type_;

}



Variable_lpd_ctor_member_type_& operator=(const Variable_lpd_ctor_member_type_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_lpd_ctor_member_vector_ : public VariableScopes
{

static constexpr auto name = "lpd_ctor_member_vector_";



Variable_lpd_ctor_member_vector_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_ctor_member_vector_;
}

virtual ~Variable_lpd_ctor_member_vector_() override = default;

Variable_lpd_ctor_member_vector_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_ctor_member_vector_;

}



Variable_lpd_ctor_member_vector_& operator=(const Variable_lpd_ctor_member_vector_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_lpd_member_ : public VariableScopes
{

static constexpr auto name = "lpd_member_";



Variable_lpd_member_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_member_;
}

virtual ~Variable_lpd_member_() override = default;

Variable_lpd_member_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_member_;

}



Variable_lpd_member_& operator=(const Variable_lpd_member_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_lpd_member_getter_unique_ : public VariableScopes
{

static constexpr auto name = "lpd_member_getter_unique_";



Variable_lpd_member_getter_unique_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_member_getter_unique_;
}

virtual ~Variable_lpd_member_getter_unique_() override = default;

Variable_lpd_member_getter_unique_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_member_getter_unique_;

}



Variable_lpd_member_getter_unique_& operator=(const Variable_lpd_member_getter_unique_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_lpd_member_optional_ : public VariableScopes
{

static constexpr auto name = "lpd_member_optional_";



Variable_lpd_member_optional_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_member_optional_;
}

virtual ~Variable_lpd_member_optional_() override = default;

Variable_lpd_member_optional_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_member_optional_;

}



Variable_lpd_member_optional_& operator=(const Variable_lpd_member_optional_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_lpd_member_standard_ : public VariableScopes
{

static constexpr auto name = "lpd_member_standard_";



Variable_lpd_member_standard_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_member_standard_;
}

virtual ~Variable_lpd_member_standard_() override = default;

Variable_lpd_member_standard_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_member_standard_;

}



Variable_lpd_member_standard_& operator=(const Variable_lpd_member_standard_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_lpd_member_vector_ : public VariableScopes
{

static constexpr auto name = "lpd_member_vector_";



Variable_lpd_member_vector_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_member_vector_;
}

virtual ~Variable_lpd_member_vector_() override = default;

Variable_lpd_member_vector_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_member_vector_;

}



Variable_lpd_member_vector_& operator=(const Variable_lpd_member_vector_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_lpd_name_ : public VariableScopes
{

static constexpr auto name = "lpd_name_";



Variable_lpd_name_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_name_;
}

virtual ~Variable_lpd_name_() override = default;

Variable_lpd_name_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_name_;

}



Variable_lpd_name_& operator=(const Variable_lpd_name_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_lpd_specific_function_ : public VariableScopes
{

static constexpr auto name = "lpd_specific_function_";



Variable_lpd_specific_function_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_specific_function_;
}

virtual ~Variable_lpd_specific_function_() override = default;

Variable_lpd_specific_function_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_specific_function_;

}



Variable_lpd_specific_function_& operator=(const Variable_lpd_specific_function_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_lpd_specific_function_prototype_ : public VariableScopes
{

static constexpr auto name = "lpd_specific_function_prototype_";



Variable_lpd_specific_function_prototype_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_specific_function_prototype_;
}

virtual ~Variable_lpd_specific_function_prototype_() override = default;

Variable_lpd_specific_function_prototype_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::lpd_specific_function_prototype_;

}



Variable_lpd_specific_function_prototype_& operator=(const Variable_lpd_specific_function_prototype_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_optional_pointer_ : public VariableScopes
{

static constexpr auto name = "optional_pointer_";



Variable_optional_pointer_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::optional_pointer_;
}

virtual ~Variable_optional_pointer_() override = default;

Variable_optional_pointer_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::optional_pointer_;

}



Variable_optional_pointer_& operator=(const Variable_optional_pointer_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_pointer_ : public VariableScopes
{

static constexpr auto name = "pointer_";



Variable_pointer_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::pointer_;
}

virtual ~Variable_pointer_() override = default;

Variable_pointer_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::pointer_;

}



Variable_pointer_& operator=(const Variable_pointer_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_right_angle_bracket_ : public VariableScopes
{

static constexpr auto name = "right_angle_bracket_";



Variable_right_angle_bracket_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::right_angle_bracket_;
}

virtual ~Variable_right_angle_bracket_() override = default;

Variable_right_angle_bracket_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::right_angle_bracket_;

}



Variable_right_angle_bracket_& operator=(const Variable_right_angle_bracket_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_right_bracket_ : public VariableScopes
{

static constexpr auto name = "right_bracket_";



Variable_right_bracket_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::right_bracket_;
}

virtual ~Variable_right_bracket_() override = default;

Variable_right_bracket_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::right_bracket_;

}



Variable_right_bracket_& operator=(const Variable_right_bracket_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_right_curly_bracket_ : public VariableScopes
{

static constexpr auto name = "right_curly_bracket_";



Variable_right_curly_bracket_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::right_curly_bracket_;
}

virtual ~Variable_right_curly_bracket_() override = default;

Variable_right_curly_bracket_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::right_curly_bracket_;

}



Variable_right_curly_bracket_& operator=(const Variable_right_curly_bracket_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};

struct Variable_target_lpd_name_ : public VariableScopes
{

static constexpr auto name = "target_lpd_name_";



Variable_target_lpd_name_() : VariableScopes()
{
	type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::target_lpd_name_;
}

virtual ~Variable_target_lpd_name_() override = default;

Variable_target_lpd_name_(MainTemplate* maintemplate_, const std::vector<VariableBase*>& variables) : VariableScopes(variables)
{
type = ::DLDL::filetemplate::lpd::lpd::MainTemplate::Type::target_lpd_name_;

}



Variable_target_lpd_name_& operator=(const Variable_target_lpd_name_& variable)
{
	if (&variable == this)
	{
		return *this;
	}

	value = variable.value;
	isString = variable.isString;

	

	return *this;
}

};


	public:
		inline static std::vector<VariableBase*> variables_to_delete = std::vector<VariableBase*>();

	public:
		std::vector<VariableBase*> variables_;

	public:
		// Members that one can directly access.
		// e.g. MainTemplate.member = "auto-generated";
		Variable_brief_description_* brief_description_ = new Variable_brief_description_();
Variable_brief_description_line_* brief_description_line_ = new Variable_brief_description_line_();
Variable_brief_description_line_content_* brief_description_line_content_ = new Variable_brief_description_line_content_();
Variable_comma_extension_* comma_extension_ = new Variable_comma_extension_();
Variable_comment_* comment_ = new Variable_comment_();
Variable_comment_content_* comment_content_ = new Variable_comment_content_();
Variable_detailed_description_* detailed_description_ = new Variable_detailed_description_();
Variable_detailed_description_line_* detailed_description_line_ = new Variable_detailed_description_line_();
Variable_detailed_description_line_content_* detailed_description_line_content_ = new Variable_detailed_description_line_content_();
Variable_explicit_lpd_namespace_* explicit_lpd_namespace_ = new Variable_explicit_lpd_namespace_();
Variable_explicit_lpd_namespace_dispatch_* explicit_lpd_namespace_dispatch_ = new Variable_explicit_lpd_namespace_dispatch_();
Variable_file_* file_ = new Variable_file_();
Variable_header_guard_* header_guard_ = new Variable_header_guard_();
Variable_ldo_full_type_* ldo_full_type_ = new Variable_ldo_full_type_();
Variable_ldo_include_* ldo_include_ = new Variable_ldo_include_();
Variable_ldo_name_* ldo_name_ = new Variable_ldo_name_();
Variable_ldo_namespace_* ldo_namespace_ = new Variable_ldo_namespace_();
Variable_ldo_type_* ldo_type_ = new Variable_ldo_type_();
Variable_left_angle_bracket_* left_angle_bracket_ = new Variable_left_angle_bracket_();
Variable_left_bracket_* left_bracket_ = new Variable_left_bracket_();
Variable_left_curly_bracket_* left_curly_bracket_ = new Variable_left_curly_bracket_();
Variable_loc_impl_* loc_impl_ = new Variable_loc_impl_();
Variable_loc_main_* loc_main_ = new Variable_loc_main_();
Variable_loc_tool_* loc_tool_ = new Variable_loc_tool_();
Variable_location_* location_ = new Variable_location_();
Variable_lpd_ctor_* lpd_ctor_ = new Variable_lpd_ctor_();
Variable_lpd_ctor_member_* lpd_ctor_member_ = new Variable_lpd_ctor_member_();
Variable_lpd_ctor_member_optional_* lpd_ctor_member_optional_ = new Variable_lpd_ctor_member_optional_();
Variable_lpd_ctor_member_standard_* lpd_ctor_member_standard_ = new Variable_lpd_ctor_member_standard_();
Variable_lpd_ctor_member_type_* lpd_ctor_member_type_ = new Variable_lpd_ctor_member_type_();
Variable_lpd_ctor_member_vector_* lpd_ctor_member_vector_ = new Variable_lpd_ctor_member_vector_();
Variable_lpd_member_* lpd_member_ = new Variable_lpd_member_();
Variable_lpd_member_getter_unique_* lpd_member_getter_unique_ = new Variable_lpd_member_getter_unique_();
Variable_lpd_member_optional_* lpd_member_optional_ = new Variable_lpd_member_optional_();
Variable_lpd_member_standard_* lpd_member_standard_ = new Variable_lpd_member_standard_();
Variable_lpd_member_vector_* lpd_member_vector_ = new Variable_lpd_member_vector_();
Variable_lpd_name_* lpd_name_ = new Variable_lpd_name_();
Variable_lpd_specific_function_* lpd_specific_function_ = new Variable_lpd_specific_function_();
Variable_lpd_specific_function_prototype_* lpd_specific_function_prototype_ = new Variable_lpd_specific_function_prototype_();
Variable_optional_pointer_* optional_pointer_ = new Variable_optional_pointer_();
Variable_pointer_* pointer_ = new Variable_pointer_();
Variable_right_angle_bracket_* right_angle_bracket_ = new Variable_right_angle_bracket_();
Variable_right_bracket_* right_bracket_ = new Variable_right_bracket_();
Variable_right_curly_bracket_* right_curly_bracket_ = new Variable_right_curly_bracket_();
Variable_target_lpd_name_* target_lpd_name_ = new Variable_target_lpd_name_();


	public:
		MainTemplate()
		{
			*brief_description_ = Variable_brief_description_(this, std::vector<VariableBase*>({ GenerateVariable("\n"), GenerateVariable(brief_description_line_->Variable_Field()) }));
*brief_description_line_ = Variable_brief_description_line_(this, std::vector<VariableBase*>({ GenerateVariable("\t *\t"), GenerateVariable(brief_description_line_content_->This()) }));
*brief_description_line_content_ = Variable_brief_description_line_content_(this, std::vector<VariableBase*>({  }));
*comma_extension_ = Variable_comma_extension_(this, std::vector<VariableBase*>({  }));
*comment_ = Variable_comment_(this, std::vector<VariableBase*>({ GenerateVariable("\t\t// "), GenerateVariable(comment_content_->This()), GenerateVariable("\n") }));
*comment_content_ = Variable_comment_content_(this, std::vector<VariableBase*>({  }));
*detailed_description_ = Variable_detailed_description_(this, std::vector<VariableBase*>({ GenerateVariable("\n"), GenerateVariable(detailed_description_line_->Variable_Field()) }));
*detailed_description_line_ = Variable_detailed_description_line_(this, std::vector<VariableBase*>({ GenerateVariable("\t *\t"), GenerateVariable(detailed_description_line_content_->This()) }));
*detailed_description_line_content_ = Variable_detailed_description_line_content_(this, std::vector<VariableBase*>({  }));
*explicit_lpd_namespace_ = Variable_explicit_lpd_namespace_(this, std::vector<VariableBase*>({ GenerateVariable(explicit_lpd_namespace_dispatch_->This()) }));
*explicit_lpd_namespace_dispatch_ = Variable_explicit_lpd_namespace_dispatch_(this, std::vector<VariableBase*>({ GenerateVariable("::"), GenerateVariable(lpd_name_->Lower()) }));
*file_ = Variable_file_(this, std::vector<VariableBase*>({  }));
*header_guard_ = Variable_header_guard_(this, std::vector<VariableBase*>({ GenerateVariable("DEAMER_LANGUAGE_DATASTRUCTURE_DEFINITION_PROPERTY_"), GenerateVariable(location_->Upper()), GenerateVariable("_"), GenerateVariable(lpd_name_->Upper()), GenerateVariable("_H") }));
*ldo_full_type_ = Variable_ldo_full_type_(this, std::vector<VariableBase*>({ GenerateVariable(ldo_namespace_->This()), GenerateVariable("::"), GenerateVariable(ldo_type_->This()), GenerateVariable(optional_pointer_->This()) }));
*ldo_include_ = Variable_ldo_include_(this, std::vector<VariableBase*>({ GenerateVariable("#include \"Deamer/Language/Type/Definition/Object/"), GenerateVariable(loc_impl_->This()), GenerateVariable("/"), GenerateVariable(target_lpd_name_->This()), GenerateVariable("/"), GenerateVariable(ldo_type_->This()), GenerateVariable("."), GenerateVariable("h\"") }));
*ldo_name_ = Variable_ldo_name_(this, std::vector<VariableBase*>({  }));
*ldo_namespace_ = Variable_ldo_namespace_(this, std::vector<VariableBase*>({ GenerateVariable("object::"), GenerateVariable(location_->This()), GenerateVariable(explicit_lpd_namespace_->This()) }));
*ldo_type_ = Variable_ldo_type_(this, std::vector<VariableBase*>({  }));
*left_angle_bracket_ = Variable_left_angle_bracket_(this, std::vector<VariableBase*>({ GenerateVariable("<") }));
*left_bracket_ = Variable_left_bracket_(this, std::vector<VariableBase*>({ GenerateVariable("{") }));
*left_curly_bracket_ = Variable_left_curly_bracket_(this, std::vector<VariableBase*>({ GenerateVariable("(") }));
*loc_impl_ = Variable_loc_impl_(this, std::vector<VariableBase*>({ GenerateVariable(loc_main_->This()) }));
*loc_main_ = Variable_loc_main_(this, std::vector<VariableBase*>({ GenerateVariable("Main") }));
*loc_tool_ = Variable_loc_tool_(this, std::vector<VariableBase*>({ GenerateVariable("Tool") }));
*location_ = Variable_location_(this, std::vector<VariableBase*>({ GenerateVariable(loc_impl_->Lower()) }));
*lpd_ctor_ = Variable_lpd_ctor_(this, std::vector<VariableBase*>({ GenerateVariable(lpd_ctor_member_->Variable_Field()) }));
*lpd_ctor_member_ = Variable_lpd_ctor_member_(this, std::vector<VariableBase*>({ GenerateVariable(comma_extension_->This()), GenerateVariable(lpd_ctor_member_type_->This()) }));
*lpd_ctor_member_optional_ = Variable_lpd_ctor_member_optional_(this, std::vector<VariableBase*>({ GenerateVariable(comment_->Variable_Field()), GenerateVariable("std::optional<"), GenerateVariable(ldo_full_type_->This()), GenerateVariable("> "), GenerateVariable(ldo_name_->This()), GenerateVariable("_") }));
*lpd_ctor_member_standard_ = Variable_lpd_ctor_member_standard_(this, std::vector<VariableBase*>({ GenerateVariable(comment_->Variable_Field()), GenerateVariable(ldo_full_type_->This()), GenerateVariable(" "), GenerateVariable(ldo_name_->This()), GenerateVariable("_") }));
*lpd_ctor_member_type_ = Variable_lpd_ctor_member_type_(this, std::vector<VariableBase*>({  }));
*lpd_ctor_member_vector_ = Variable_lpd_ctor_member_vector_(this, std::vector<VariableBase*>({ GenerateVariable(comment_->Variable_Field()), GenerateVariable("std::vector<"), GenerateVariable(ldo_full_type_->This()), GenerateVariable("> "), GenerateVariable(ldo_name_->This()), GenerateVariable("_") }));
*lpd_member_ = Variable_lpd_member_(this, std::vector<VariableBase*>({  }));
*lpd_member_getter_unique_ = Variable_lpd_member_getter_unique_(this, std::vector<VariableBase*>({  }));
*lpd_member_optional_ = Variable_lpd_member_optional_(this, std::vector<VariableBase*>({ GenerateVariable("\t\t"), GenerateVariable(comment_->Variable_Field()), GenerateVariable("std::optional<"), GenerateVariable(ldo_full_type_->This()), GenerateVariable("> "), GenerateVariable(ldo_name_->This()), GenerateVariable(";") }));
*lpd_member_standard_ = Variable_lpd_member_standard_(this, std::vector<VariableBase*>({ GenerateVariable("\t\t"), GenerateVariable(comment_->Variable_Field()), GenerateVariable(ldo_full_type_->This()), GenerateVariable(" "), GenerateVariable(ldo_name_->This()), GenerateVariable(";") }));
*lpd_member_vector_ = Variable_lpd_member_vector_(this, std::vector<VariableBase*>({ GenerateVariable("\t\t"), GenerateVariable(comment_->Variable_Field()), GenerateVariable("std::vector<"), GenerateVariable(ldo_full_type_->This()), GenerateVariable("> "), GenerateVariable(ldo_name_->This()), GenerateVariable(";") }));
*lpd_name_ = Variable_lpd_name_(this, std::vector<VariableBase*>({  }));
*lpd_specific_function_ = Variable_lpd_specific_function_(this, std::vector<VariableBase*>({ GenerateVariable("\t\t"), GenerateVariable(lpd_specific_function_prototype_->This()), GenerateVariable(";") }));
*lpd_specific_function_prototype_ = Variable_lpd_specific_function_prototype_(this, std::vector<VariableBase*>({  }));
*optional_pointer_ = Variable_optional_pointer_(this, std::vector<VariableBase*>({ GenerateVariable(pointer_->This()) }));
*pointer_ = Variable_pointer_(this, std::vector<VariableBase*>({ GenerateVariable("*") }));
*right_angle_bracket_ = Variable_right_angle_bracket_(this, std::vector<VariableBase*>({ GenerateVariable(">") }));
*right_bracket_ = Variable_right_bracket_(this, std::vector<VariableBase*>({ GenerateVariable("}") }));
*right_curly_bracket_ = Variable_right_curly_bracket_(this, std::vector<VariableBase*>({ GenerateVariable(")") }));
*target_lpd_name_ = Variable_target_lpd_name_(this, std::vector<VariableBase*>({  }));


			variables_.emplace_back(brief_description_);
variables_.emplace_back(brief_description_line_);
variables_.emplace_back(brief_description_line_content_);
variables_.emplace_back(comma_extension_);
variables_.emplace_back(comment_);
variables_.emplace_back(comment_content_);
variables_.emplace_back(detailed_description_);
variables_.emplace_back(detailed_description_line_);
variables_.emplace_back(detailed_description_line_content_);
variables_.emplace_back(explicit_lpd_namespace_);
variables_.emplace_back(explicit_lpd_namespace_dispatch_);
variables_.emplace_back(file_);
variables_.emplace_back(header_guard_);
variables_.emplace_back(ldo_full_type_);
variables_.emplace_back(ldo_include_);
variables_.emplace_back(ldo_name_);
variables_.emplace_back(ldo_namespace_);
variables_.emplace_back(ldo_type_);
variables_.emplace_back(left_angle_bracket_);
variables_.emplace_back(left_bracket_);
variables_.emplace_back(left_curly_bracket_);
variables_.emplace_back(loc_impl_);
variables_.emplace_back(loc_main_);
variables_.emplace_back(loc_tool_);
variables_.emplace_back(location_);
variables_.emplace_back(lpd_ctor_);
variables_.emplace_back(lpd_ctor_member_);
variables_.emplace_back(lpd_ctor_member_optional_);
variables_.emplace_back(lpd_ctor_member_standard_);
variables_.emplace_back(lpd_ctor_member_type_);
variables_.emplace_back(lpd_ctor_member_vector_);
variables_.emplace_back(lpd_member_);
variables_.emplace_back(lpd_member_getter_unique_);
variables_.emplace_back(lpd_member_optional_);
variables_.emplace_back(lpd_member_standard_);
variables_.emplace_back(lpd_member_vector_);
variables_.emplace_back(lpd_name_);
variables_.emplace_back(lpd_specific_function_);
variables_.emplace_back(lpd_specific_function_prototype_);
variables_.emplace_back(optional_pointer_);
variables_.emplace_back(pointer_);
variables_.emplace_back(right_angle_bracket_);
variables_.emplace_back(right_bracket_);
variables_.emplace_back(right_curly_bracket_);
variables_.emplace_back(target_lpd_name_);

		}

		virtual ~MainTemplate()
		{
			for(auto* variable : variables_to_delete)
			{
				delete variable;
			}

			variables_to_delete.clear();
		}

	public:
		// Default DST functions

		/*!	\fn GetOutput
		 *
		 *	\brief returns the output with the given the current state.
		 */
		std::string GetOutput()
		{
			return file_->Content()->GetValue();
		}

		/*!	\fn GetVariables
		 *
		 *	\brief Returns all top level variables known in this template.
		 */
		std::vector<VariableBase*> GetVariables()
		{
			return variables_;
		}

	public:
	};
}

#endif // DLDL_FILETEMPLATE_LPD_LPD_MAINTEMPLATE_h
