#ifndef DLDL_GENERATION_DLDL_GENERATION_H
#define DLDL_GENERATION_DLDL_GENERATION_H

// This is a generated file for the language: DLDL_GENERATION

namespace DLDL_GENERATION
{
}

#endif // DLDL_GENERATION_DLDL_GENERATION_H