#ifndef DLDL_GRAMMAR_PRODUCTION_RULE_AST_NODE_ENDING_USELESS_SYMBOLS_H
#define DLDL_GRAMMAR_PRODUCTION_RULE_AST_NODE_ENDING_USELESS_SYMBOLS_H

#include "DLDL_GRAMMAR_PRODUCTION_RULE/Ast/Node/DLDL_GRAMMAR_PRODUCTION_RULE.h"
#include <Deamer/External/Cpp/Ast/Node.h>

namespace DLDL_GRAMMAR_PRODUCTION_RULE { namespace ast { namespace node {

	class ENDING_USELESS_SYMBOLS : public DLDL_GRAMMAR_PRODUCTION_RULE<ENDING_USELESS_SYMBOLS>
	{
	private:
	public:
		ENDING_USELESS_SYMBOLS(deamer::external::cpp::ast::NodeInformation information_)
		: DLDL_GRAMMAR_PRODUCTION_RULE<ENDING_USELESS_SYMBOLS>(information_, {}, {})
		{
		}
	};

}}}

#endif // DLDL_GRAMMAR_PRODUCTION_RULE_AST_NODE_ENDING_USELESS_SYMBOLS_H
