#ifndef DLDL_LDOSTRUCT_DLDL_LDOSTRUCT_H
#define DLDL_LDOSTRUCT_DLDL_LDOSTRUCT_H

// This is a generated file for the language: DLDL_LDOSTRUCT

namespace DLDL_LDOSTRUCT
{
}

#endif // DLDL_LDOSTRUCT_DLDL_LDOSTRUCT_H