#ifndef DLDL_FILETEMPLATE_VALUEHTEMPLATE_h
#define DLDL_FILETEMPLATE_VALUEHTEMPLATE_h

#include <string>
#include <variant>
#include <vector>

namespace DLDL::filetemplate
{
	/*!	\class ValueHTemplate
	 *
	 *	\brief Generates code for "ValueHTemplate"
	 *
	 *	\details This is generated by DST.
	 *	For more information visit: https://github.com/Deruago/DeamerStringTemplate
	 */
	class ValueHTemplate
	{
	public:
		enum class Type
		{
			Unknown,
			Scope,

			// User defined types
			file_,
			header_guard_,
			language_full_name_,
			language_full_name_slash_,
			language_full_name_underscore_,
			left_angle_bracket_,
			left_bracket_,
			left_curly_bracket_,
			right_angle_bracket_,
			right_bracket_,
			right_curly_bracket_,
			unknown_reference_,
			unknown_reference_declaration_,
			value_abstraction_declaration_,
			value_abstraction_name_,
			value_abstraction_primary_name_,
			value_object_declaration_,
			value_object_name_,
			value_rule_name_,

		};

		enum class ScopeType
		{
			Unknown,

			// Default
			Default_,
			Upper_,
			Lower_,

			Snake_,
			Slash_,
			BackSlash_,
			Colon_,
			DoubleColon_,

			Variable_Field_,
			Variable_Field_Separator_,
			Function_Field_,
			Function_Field_Separator_,

		};

		static constexpr const char*
		ConvertEnumToName(::DLDL::filetemplate::ValueHTemplate::Type enumerationValue)
		{
			switch (enumerationValue)
			{
			case ::DLDL::filetemplate::ValueHTemplate::Type::Unknown: {
				return "Unknown";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::Scope: {
				return "Scope";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::file_: {
				return "file";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::header_guard_: {
				return "header_guard";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::language_full_name_: {
				return "language_full_name";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::language_full_name_slash_: {
				return "language_full_name_slash";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::language_full_name_underscore_: {
				return "language_full_name_underscore";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::left_angle_bracket_: {
				return "left_angle_bracket";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::left_bracket_: {
				return "left_bracket";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::left_curly_bracket_: {
				return "left_curly_bracket";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::right_angle_bracket_: {
				return "right_angle_bracket";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::right_bracket_: {
				return "right_bracket";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::right_curly_bracket_: {
				return "right_curly_bracket";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::unknown_reference_: {
				return "unknown_reference";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::unknown_reference_declaration_: {
				return "unknown_reference_declaration";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::value_abstraction_declaration_: {
				return "value_abstraction_declaration";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::value_abstraction_name_: {
				return "value_abstraction_name";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::value_abstraction_primary_name_: {
				return "value_abstraction_primary_name";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::value_object_declaration_: {
				return "value_object_declaration";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::value_object_name_: {
				return "value_object_name";
			}

			case ::DLDL::filetemplate::ValueHTemplate::Type::value_rule_name_: {
				return "value_rule_name";
			}
			}

			return "";
		}

	public:
		struct VariableBase
		{
			// The value is either a string
			// or a vector of variables.
			std::variant<std::string, std::vector<VariableBase*>> value;
			bool isString = true;

			::DLDL::filetemplate::ValueHTemplate::Type type =
				::DLDL::filetemplate::ValueHTemplate::Type::Unknown;

			VariableBase() : VariableBase(std::vector<VariableBase*>())
			{
			}

			virtual ~VariableBase() = default;

			VariableBase(const char* text)
			{
				isString = true;
				value = text;
			}

			VariableBase(const std::string& text)
			{
				isString = true;
				value = text;
			}

			VariableBase(std::vector<VariableBase*> variables)
			{
				isString = false;
				value = variables;
			}

			VariableBase* This()
			{
				return this;
			}

			virtual std::string GetValue()
			{
				if (isString)
				{
					return std::get<std::string>(value);
				}
				else
				{
					std::string output;
					auto& variables = std::get<std::vector<VariableBase*>>(value);
					for (auto* variable : variables)
					{
						output += variable->GetValue();
					}
					return output;
				}
			}

			std::string GetName()
			{
				return ConvertEnumToName(type);
			}

			VariableBase& operator=(const std::string& variable)
			{
				return Set(variable);
			}

			VariableBase& operator=(VariableBase* variable)
			{
				return Set(variable);
			}

			VariableBase& operator+=(VariableBase* variable)
			{
				return Add(variable);
			}

			VariableBase& operator+=(const std::string& variable)
			{
				return Add(variable);
			}

			VariableBase& Set(const std::string& variable)
			{
				value = variable;
				isString = true;

				return *this;
			}

			VariableBase& Set(VariableBase* variable)
			{
				if (variable == this)
				{
					return *this;
				}

				value = variable->value;
				isString = variable->isString;

				return *this;
			}

			VariableBase& Add(const std::string& variable)
			{
				if (isString)
				{
					auto& text = std::get<std::string>(value);
					text += variable;
					value = text;
				}
				else
				{
					auto& vector = std::get<std::vector<VariableBase*>>(value);
					vector.push_back(new VariableBase(variable));
					value = vector;
				}

				return *this;
			}

			VariableBase& Add(VariableBase* variable)
			{
				if (variable == this)
				{
					return *this;
				}

				if (isString)
				{
					// convert current -> variablebase
					// then create a vector.
					auto& currentValue = std::get<std::string>(value);
					auto* currentValueAsVariableBase = new VariableBase(currentValue);
					value = std::vector<VariableBase*>({currentValueAsVariableBase, variable});

					isString = false;
				}
				else
				{
					auto& vector = std::get<std::vector<VariableBase*>>(value);
					vector.push_back(variable);
					value = vector;
				}

				return *this;
			}

			void Clear()
			{
				if (isString)
				{
					value = "";
				}
				else
				{
					value = std::vector<VariableBase*>();
				}
			}

			void* operator new(size_t size)
			{
				void* newVariable = ::operator new(size);
				variables_to_delete.emplace_back(static_cast<VariableBase*>(newVariable));

				return newVariable;
			}
		};

		static VariableBase* GenerateVariable(VariableBase* variable)
		{
			return variable;
		}

		static VariableBase* GenerateVariable(const std::string& variable)
		{
			return new VariableBase(variable);
		}

		struct VariableScope : public VariableBase
		{
			::DLDL::filetemplate::ValueHTemplate::ScopeType scope_type =
				::DLDL::filetemplate::ValueHTemplate::ScopeType::Unknown;
			bool isReserved = false;

			VariableScope(::DLDL::filetemplate::ValueHTemplate::ScopeType scope_type_,
						  bool isReserved_ = false)
				: VariableBase(),
				  scope_type(scope_type_),
				  isReserved(isReserved_)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::Scope;
			}

			VariableScope(const char* text,
						  ::DLDL::filetemplate::ValueHTemplate::ScopeType scope_type_,
						  bool isReserved_ = false)
				: VariableBase(text),
				  scope_type(scope_type_),
				  isReserved(isReserved_)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::Scope;
			}

			VariableScope(std::vector<VariableBase*> variable,
						  ::DLDL::filetemplate::ValueHTemplate::ScopeType scope_type_,
						  bool isReserved_ = false)
				: VariableBase(variable),
				  scope_type(scope_type_),
				  isReserved(isReserved_)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::Scope;
			}
		};

		struct Variable_ReservedScope_Upper : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Upper(VariableBase* base_)
				: VariableScope(::DLDL::filetemplate::ValueHTemplate::ScopeType::Upper_, true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string upperVariant;
				std::string currentValue = base->GetValue();

				for (const auto character : currentValue)
				{
					upperVariant += std::toupper(character);
				}

				return upperVariant;
			}
		};

		struct Variable_ReservedScope_Lower : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Lower(VariableBase* base_)
				: VariableScope(::DLDL::filetemplate::ValueHTemplate::ScopeType::Lower_, true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string lowerVariant;
				std::string currentValue = base->GetValue();

				for (const auto character : currentValue)
				{
					lowerVariant += std::tolower(character);
				}

				return lowerVariant;
			}
		};

		struct Variable_ReservedScope_Snake : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Snake(VariableBase* base_)
				: VariableScope(::DLDL::filetemplate::ValueHTemplate::ScopeType::Snake_, true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string snakeVariant;
				std::string currentValue = base->GetValue();

				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						snakeVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}

						snakeVariant += '_';
						lastWasNonAlpha = true;
					}
				}

				// If it contains text
				// remove the tail
				if (!snakeVariant.empty() && lastWasNonAlpha)
				{
					snakeVariant.pop_back();
				}

				return snakeVariant;
			}
		};

		struct Variable_ReservedScope_Slash : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_Slash(VariableBase* base_)
				: VariableScope(::DLDL::filetemplate::ValueHTemplate::ScopeType::Slash_, true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string slashVariant;
				std::string currentValue = base->GetValue();

				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						slashVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}

						slashVariant += '/';
						lastWasNonAlpha = true;
					}
				}

				// If it contains text
				// remove the tail
				if (!slashVariant.empty() && lastWasNonAlpha)
				{
					slashVariant.pop_back();
				}

				return slashVariant;
			}
		};

		struct Variable_ReservedScope_DoubleColon : public VariableScope
		{
			VariableBase* base;
			Variable_ReservedScope_DoubleColon(VariableBase* base_)
				: VariableScope(::DLDL::filetemplate::ValueHTemplate::ScopeType::DoubleColon_,
								true),
				  base(base_)
			{
			}

			virtual std::string GetValue() override
			{
				std::string doubleColonVariant;
				std::string currentValue = base->GetValue();

				bool lastWasNonAlpha = true;
				for (const auto character : currentValue)
				{
					if (std::isalpha(character))
					{
						doubleColonVariant += character;
						lastWasNonAlpha = false;
					}
					else
					{
						if (lastWasNonAlpha)
						{
							continue;
						}

						doubleColonVariant += "::";
						lastWasNonAlpha = true;
					}
				}

				// If it contains text
				// remove the tail
				if (!doubleColonVariant.empty() && lastWasNonAlpha)
				{
					doubleColonVariant.pop_back();
					doubleColonVariant.pop_back();
				}

				return doubleColonVariant;
			}
		};

		struct VariableScopes : public VariableBase
		{
			// Default scopes
			VariableBase* default_ =
				new VariableScope(::DLDL::filetemplate::ValueHTemplate::ScopeType::Default_, true);
			VariableBase* upper_ = new Variable_ReservedScope_Upper(this);
			VariableBase* lower_ = new Variable_ReservedScope_Lower(this);

			VariableBase* snake_ = new Variable_ReservedScope_Snake(this);
			VariableBase* slash_ = new Variable_ReservedScope_Slash(this);
			VariableBase* double_colon_ = new Variable_ReservedScope_DoubleColon(this);

			VariableBase* variable_field_ = new VariableScope(
				::DLDL::filetemplate::ValueHTemplate::ScopeType::Variable_Field_, true);
			VariableBase* variable_field_separator_ = new VariableScope(
				"\n", ::DLDL::filetemplate::ValueHTemplate::ScopeType::Variable_Field_Separator_,
				true);

			// Ctor
			VariableScopes() : VariableBase()
			{
			}

			VariableScopes(const char* text) : VariableBase(text)
			{
			}

			VariableScopes(const std::string& text) : VariableBase(text)
			{
			}

			VariableScopes(std::vector<VariableBase*> variables) : VariableBase(variables)
			{
			}

			// Dtor
			virtual ~VariableScopes() override = default;

			// Calls
			VariableBase* Default()
			{
				return default_;
			}
			VariableBase* Upper()
			{
				return upper_;
			}

			VariableBase* Lower()
			{
				return lower_;
			}

			VariableBase* Underscore()
			{
				return snake_;
			}

			VariableBase* Snake()
			{
				return snake_;
			}

			VariableBase* Slash()
			{
				return slash_;
			}

			VariableBase* DoubleColon()
			{
				return double_colon_;
			}

			VariableBase* Variable_Field()
			{
				return variable_field_;
			}

			VariableBase* Variable_Field_Separator()
			{
				return variable_field_separator_;
			}

			void ExpandVariableField()
			{
				// currentvalue + separator
				const auto currentValue = GetValue() + Variable_Field_Separator()->GetValue();
				*Variable_Field() += currentValue;
			}
		};

	public:
		struct Variable_file_ : public VariableScopes
		{
			static constexpr auto name = "file_";

			VariableBase* Content_ = GenerateVariable("");
			VariableBase* Class_postfix_ = GenerateVariable("");
			VariableBase* Extension_ = GenerateVariable("");
			VariableBase* File_name_ = GenerateVariable("");
			VariableBase* Namespace_ = GenerateVariable("");
			VariableBase* Target_language_ = GenerateVariable("");

			Variable_file_() : VariableScopes()
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::file_;
			}

			virtual ~Variable_file_() override = default;

			Variable_file_(ValueHTemplate* valuehtemplate_,
						   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::file_;
				*static_cast<VariableBase*>(Content_) = VariableBase(std::vector<VariableBase*>(
					{GenerateVariable(
						 "/* \n * This file is auto-generated and auto-maintained by DLDL\n * Do "
						 "not change code in this as it can be overwritten"),
					 GenerateVariable("."),
					 GenerateVariable(
						 "\n *\n * For more information see the DLDL repo: https://github"),
					 GenerateVariable("."),
					 GenerateVariable(
						 "com/Deruago/DLDL\n * For more information about Deamer: https://github"),
					 GenerateVariable("."),
					 GenerateVariable("com/Deruago/theDeamerProject\n */\n\n#ifndef "),
					 GenerateVariable(valuehtemplate_->header_guard_->This()),
					 GenerateVariable("\n#define "),
					 GenerateVariable(valuehtemplate_->header_guard_->This()),
					 GenerateVariable(
						 "\n\n#include "
						 "\"Deamer/Language/Generator/Definition/Property/User/Main/Value"),
					 GenerateVariable("."),
					 GenerateVariable(
						 "h\"\n#include "
						 "\"Deamer/Language/Type/Definition/Object/Special/Uninitialized"),
					 GenerateVariable("."),
					 GenerateVariable("h\"\n\nnamespace "),
					 GenerateVariable(valuehtemplate_->language_full_name_->This()),
					 GenerateVariable("\n"),
					 GenerateVariable("{"),
					 GenerateVariable("\n\tclass Language;\n\n\tclass Value : public "
									  "::deamer::language::generator::definition::property::user::"
									  "Value<\n\t\t\t\t\t\t\t\t::"),
					 GenerateVariable(valuehtemplate_->language_full_name_->This()),
					 GenerateVariable("::Language>\n\t"),
					 GenerateVariable("{"),
					 GenerateVariable("\n\tpublic:\n\t// Value Objects (Rules)\n"),
					 GenerateVariable(valuehtemplate_->value_object_declaration_->Variable_Field()),
					 GenerateVariable("\n\n\t// Value Abstractions\n"),
					 GenerateVariable(
						 valuehtemplate_->value_abstraction_declaration_->Variable_Field()),
					 GenerateVariable("\n\tprivate:\n\t\t"),
					 GenerateVariable(
						 valuehtemplate_->unknown_reference_declaration_->Variable_Field()),
					 GenerateVariable("\n\n\tpublic:\n\t\tValue("),
					 GenerateVariable(valuehtemplate_->language_full_name_->This()),
					 GenerateVariable(
						 "::Language* language);\n\t\t\n\t\tvoid GenerateObjects() override;\n\t"),
					 GenerateVariable("}"),
					 GenerateVariable(";\n"),
					 GenerateVariable("}"),
					 GenerateVariable("\n\n#endif // "),
					 GenerateVariable(valuehtemplate_->header_guard_->This()),
					 GenerateVariable("\n")}));
				Content_->type = ::DLDL::filetemplate::ValueHTemplate::Type::Scope;

				*static_cast<VariableBase*>(Class_postfix_) =
					VariableBase(std::vector<VariableBase*>({}));
				Class_postfix_->type = ::DLDL::filetemplate::ValueHTemplate::Type::Scope;

				*static_cast<VariableBase*>(Extension_) =
					VariableBase(std::vector<VariableBase*>({GenerateVariable("h")}));
				Extension_->type = ::DLDL::filetemplate::ValueHTemplate::Type::Scope;

				*static_cast<VariableBase*>(File_name_) =
					VariableBase(std::vector<VariableBase*>({GenerateVariable("ValueH")}));
				File_name_->type = ::DLDL::filetemplate::ValueHTemplate::Type::Scope;

				*static_cast<VariableBase*>(Namespace_) = VariableBase(
					std::vector<VariableBase*>({GenerateVariable("DLDL::filetemplate")}));
				Namespace_->type = ::DLDL::filetemplate::ValueHTemplate::Type::Scope;

				*static_cast<VariableBase*>(Target_language_) =
					VariableBase(std::vector<VariableBase*>({GenerateVariable("C++")}));
				Target_language_->type = ::DLDL::filetemplate::ValueHTemplate::Type::Scope;
			}

			VariableBase* Content() const
			{
				return Content_;
			}

			VariableBase* Class_postfix() const
			{
				return Class_postfix_;
			}

			VariableBase* Extension() const
			{
				return Extension_;
			}

			VariableBase* File_name() const
			{
				return File_name_;
			}

			VariableBase* Namespace() const
			{
				return Namespace_;
			}

			VariableBase* Target_language() const
			{
				return Target_language_;
			}

			Variable_file_& operator=(const Variable_file_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				*Content_ = *variable.Content_;
				*Class_postfix_ = *variable.Class_postfix_;
				*Extension_ = *variable.Extension_;
				*File_name_ = *variable.File_name_;
				*Namespace_ = *variable.Namespace_;
				*Target_language_ = *variable.Target_language_;

				return *this;
			}
		};

		struct Variable_header_guard_ : public VariableScopes
		{
			static constexpr auto name = "header_guard_";

			Variable_header_guard_() : VariableScopes()
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::header_guard_;
			}

			virtual ~Variable_header_guard_() override = default;

			Variable_header_guard_(ValueHTemplate* valuehtemplate_,
								   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::header_guard_;
			}

			Variable_header_guard_& operator=(const Variable_header_guard_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_language_full_name_ : public VariableScopes
		{
			static constexpr auto name = "language_full_name_";

			Variable_language_full_name_() : VariableScopes()
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::language_full_name_;
			}

			virtual ~Variable_language_full_name_() override = default;

			Variable_language_full_name_(ValueHTemplate* valuehtemplate_,
										 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::language_full_name_;
			}

			Variable_language_full_name_& operator=(const Variable_language_full_name_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_language_full_name_slash_ : public VariableScopes
		{
			static constexpr auto name = "language_full_name_slash_";

			Variable_language_full_name_slash_() : VariableScopes()
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::language_full_name_slash_;
			}

			virtual ~Variable_language_full_name_slash_() override = default;

			Variable_language_full_name_slash_(ValueHTemplate* valuehtemplate_,
											   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::language_full_name_slash_;
			}

			Variable_language_full_name_slash_&
			operator=(const Variable_language_full_name_slash_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_language_full_name_underscore_ : public VariableScopes
		{
			static constexpr auto name = "language_full_name_underscore_";

			Variable_language_full_name_underscore_() : VariableScopes()
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::language_full_name_underscore_;
			}

			virtual ~Variable_language_full_name_underscore_() override = default;

			Variable_language_full_name_underscore_(ValueHTemplate* valuehtemplate_,
													const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::language_full_name_underscore_;
			}

			Variable_language_full_name_underscore_&
			operator=(const Variable_language_full_name_underscore_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_left_angle_bracket_ : public VariableScopes
		{
			static constexpr auto name = "left_angle_bracket_";

			Variable_left_angle_bracket_() : VariableScopes()
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::left_angle_bracket_;
			}

			virtual ~Variable_left_angle_bracket_() override = default;

			Variable_left_angle_bracket_(ValueHTemplate* valuehtemplate_,
										 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::left_angle_bracket_;
			}

			Variable_left_angle_bracket_& operator=(const Variable_left_angle_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_left_bracket_ : public VariableScopes
		{
			static constexpr auto name = "left_bracket_";

			Variable_left_bracket_() : VariableScopes()
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::left_bracket_;
			}

			virtual ~Variable_left_bracket_() override = default;

			Variable_left_bracket_(ValueHTemplate* valuehtemplate_,
								   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::left_bracket_;
			}

			Variable_left_bracket_& operator=(const Variable_left_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_left_curly_bracket_ : public VariableScopes
		{
			static constexpr auto name = "left_curly_bracket_";

			Variable_left_curly_bracket_() : VariableScopes()
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::left_curly_bracket_;
			}

			virtual ~Variable_left_curly_bracket_() override = default;

			Variable_left_curly_bracket_(ValueHTemplate* valuehtemplate_,
										 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::left_curly_bracket_;
			}

			Variable_left_curly_bracket_& operator=(const Variable_left_curly_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_right_angle_bracket_ : public VariableScopes
		{
			static constexpr auto name = "right_angle_bracket_";

			Variable_right_angle_bracket_() : VariableScopes()
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::right_angle_bracket_;
			}

			virtual ~Variable_right_angle_bracket_() override = default;

			Variable_right_angle_bracket_(ValueHTemplate* valuehtemplate_,
										  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::right_angle_bracket_;
			}

			Variable_right_angle_bracket_& operator=(const Variable_right_angle_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_right_bracket_ : public VariableScopes
		{
			static constexpr auto name = "right_bracket_";

			Variable_right_bracket_() : VariableScopes()
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::right_bracket_;
			}

			virtual ~Variable_right_bracket_() override = default;

			Variable_right_bracket_(ValueHTemplate* valuehtemplate_,
									const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::right_bracket_;
			}

			Variable_right_bracket_& operator=(const Variable_right_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_right_curly_bracket_ : public VariableScopes
		{
			static constexpr auto name = "right_curly_bracket_";

			Variable_right_curly_bracket_() : VariableScopes()
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::right_curly_bracket_;
			}

			virtual ~Variable_right_curly_bracket_() override = default;

			Variable_right_curly_bracket_(ValueHTemplate* valuehtemplate_,
										  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::right_curly_bracket_;
			}

			Variable_right_curly_bracket_& operator=(const Variable_right_curly_bracket_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_unknown_reference_ : public VariableScopes
		{
			static constexpr auto name = "unknown_reference_";

			Variable_unknown_reference_() : VariableScopes()
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::unknown_reference_;
			}

			virtual ~Variable_unknown_reference_() override = default;

			Variable_unknown_reference_(ValueHTemplate* valuehtemplate_,
										const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::unknown_reference_;
			}

			Variable_unknown_reference_& operator=(const Variable_unknown_reference_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_unknown_reference_declaration_ : public VariableScopes
		{
			static constexpr auto name = "unknown_reference_declaration_";

			Variable_unknown_reference_declaration_() : VariableScopes()
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::unknown_reference_declaration_;
			}

			virtual ~Variable_unknown_reference_declaration_() override = default;

			Variable_unknown_reference_declaration_(ValueHTemplate* valuehtemplate_,
													const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::unknown_reference_declaration_;
			}

			Variable_unknown_reference_declaration_&
			operator=(const Variable_unknown_reference_declaration_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_value_abstraction_declaration_ : public VariableScopes
		{
			static constexpr auto name = "value_abstraction_declaration_";

			Variable_value_abstraction_declaration_() : VariableScopes()
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::value_abstraction_declaration_;
			}

			virtual ~Variable_value_abstraction_declaration_() override = default;

			Variable_value_abstraction_declaration_(ValueHTemplate* valuehtemplate_,
													const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::value_abstraction_declaration_;
			}

			Variable_value_abstraction_declaration_&
			operator=(const Variable_value_abstraction_declaration_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_value_abstraction_name_ : public VariableScopes
		{
			static constexpr auto name = "value_abstraction_name_";

			Variable_value_abstraction_name_() : VariableScopes()
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::value_abstraction_name_;
			}

			virtual ~Variable_value_abstraction_name_() override = default;

			Variable_value_abstraction_name_(ValueHTemplate* valuehtemplate_,
											 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::value_abstraction_name_;
			}

			Variable_value_abstraction_name_&
			operator=(const Variable_value_abstraction_name_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_value_abstraction_primary_name_ : public VariableScopes
		{
			static constexpr auto name = "value_abstraction_primary_name_";

			Variable_value_abstraction_primary_name_() : VariableScopes()
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::value_abstraction_primary_name_;
			}

			virtual ~Variable_value_abstraction_primary_name_() override = default;

			Variable_value_abstraction_primary_name_(ValueHTemplate* valuehtemplate_,
													 const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::value_abstraction_primary_name_;
			}

			Variable_value_abstraction_primary_name_&
			operator=(const Variable_value_abstraction_primary_name_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_value_object_declaration_ : public VariableScopes
		{
			static constexpr auto name = "value_object_declaration_";

			Variable_value_object_declaration_() : VariableScopes()
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::value_object_declaration_;
			}

			virtual ~Variable_value_object_declaration_() override = default;

			Variable_value_object_declaration_(ValueHTemplate* valuehtemplate_,
											   const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::value_object_declaration_;
			}

			Variable_value_object_declaration_&
			operator=(const Variable_value_object_declaration_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_value_object_name_ : public VariableScopes
		{
			static constexpr auto name = "value_object_name_";

			Variable_value_object_name_() : VariableScopes()
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::value_object_name_;
			}

			virtual ~Variable_value_object_name_() override = default;

			Variable_value_object_name_(ValueHTemplate* valuehtemplate_,
										const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::value_object_name_;
			}

			Variable_value_object_name_& operator=(const Variable_value_object_name_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

		struct Variable_value_rule_name_ : public VariableScopes
		{
			static constexpr auto name = "value_rule_name_";

			Variable_value_rule_name_() : VariableScopes()
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::value_rule_name_;
			}

			virtual ~Variable_value_rule_name_() override = default;

			Variable_value_rule_name_(ValueHTemplate* valuehtemplate_,
									  const std::vector<VariableBase*>& variables)
				: VariableScopes(variables)
			{
				type = ::DLDL::filetemplate::ValueHTemplate::Type::value_rule_name_;
			}

			Variable_value_rule_name_& operator=(const Variable_value_rule_name_& variable)
			{
				if (&variable == this)
				{
					return *this;
				}

				value = variable.value;
				isString = variable.isString;

				return *this;
			}
		};

	public:
		inline static std::vector<VariableBase*> variables_to_delete = std::vector<VariableBase*>();

	public:
		std::vector<VariableBase*> variables_;

	public:
		// Members that one can directly access.
		// e.g. ValueHTemplate.member = "auto-generated";
		Variable_file_* file_ = new Variable_file_();
		Variable_header_guard_* header_guard_ = new Variable_header_guard_();
		Variable_language_full_name_* language_full_name_ = new Variable_language_full_name_();
		Variable_language_full_name_slash_* language_full_name_slash_ =
			new Variable_language_full_name_slash_();
		Variable_language_full_name_underscore_* language_full_name_underscore_ =
			new Variable_language_full_name_underscore_();
		Variable_left_angle_bracket_* left_angle_bracket_ = new Variable_left_angle_bracket_();
		Variable_left_bracket_* left_bracket_ = new Variable_left_bracket_();
		Variable_left_curly_bracket_* left_curly_bracket_ = new Variable_left_curly_bracket_();
		Variable_right_angle_bracket_* right_angle_bracket_ = new Variable_right_angle_bracket_();
		Variable_right_bracket_* right_bracket_ = new Variable_right_bracket_();
		Variable_right_curly_bracket_* right_curly_bracket_ = new Variable_right_curly_bracket_();
		Variable_unknown_reference_* unknown_reference_ = new Variable_unknown_reference_();
		Variable_unknown_reference_declaration_* unknown_reference_declaration_ =
			new Variable_unknown_reference_declaration_();
		Variable_value_abstraction_declaration_* value_abstraction_declaration_ =
			new Variable_value_abstraction_declaration_();
		Variable_value_abstraction_name_* value_abstraction_name_ =
			new Variable_value_abstraction_name_();
		Variable_value_abstraction_primary_name_* value_abstraction_primary_name_ =
			new Variable_value_abstraction_primary_name_();
		Variable_value_object_declaration_* value_object_declaration_ =
			new Variable_value_object_declaration_();
		Variable_value_object_name_* value_object_name_ = new Variable_value_object_name_();
		Variable_value_rule_name_* value_rule_name_ = new Variable_value_rule_name_();

	public:
		ValueHTemplate()
		{
			*file_ = Variable_file_(this, std::vector<VariableBase*>({}));
			*header_guard_ = Variable_header_guard_(
				this, std::vector<VariableBase*>(
						  {GenerateVariable(language_full_name_underscore_->Upper()),
						   GenerateVariable("_VALUE_H")}));
			*language_full_name_ =
				Variable_language_full_name_(this, std::vector<VariableBase*>({}));
			*language_full_name_slash_ =
				Variable_language_full_name_slash_(this, std::vector<VariableBase*>({}));
			*language_full_name_underscore_ =
				Variable_language_full_name_underscore_(this, std::vector<VariableBase*>({}));
			*left_angle_bracket_ = Variable_left_angle_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable("<")}));
			*left_bracket_ =
				Variable_left_bracket_(this, std::vector<VariableBase*>({GenerateVariable("{")}));
			*left_curly_bracket_ = Variable_left_curly_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable("(")}));
			*right_angle_bracket_ = Variable_right_angle_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable(">")}));
			*right_bracket_ =
				Variable_right_bracket_(this, std::vector<VariableBase*>({GenerateVariable("}")}));
			*right_curly_bracket_ = Variable_right_curly_bracket_(
				this, std::vector<VariableBase*>({GenerateVariable(")")}));
			*unknown_reference_ = Variable_unknown_reference_(this, std::vector<VariableBase*>({}));
			*unknown_reference_declaration_ = Variable_unknown_reference_declaration_(
				this,
				std::vector<VariableBase*>(
					{GenerateVariable("::deamer::type::SafeReserve<::deamer::language::type::"
									  "definition::object::special::Uninitialized<::deamer::"
									  "language::type::definition::object::main::NonTerminal>> "),
					 GenerateVariable(unknown_reference_->This()), GenerateVariable(";")}));
			*value_abstraction_declaration_ = Variable_value_abstraction_declaration_(
				this,
				std::vector<VariableBase*>(
					{GenerateVariable("::deamer::type::SafeReserve<::deamer::language::type::"
									  "definition::object::main::ValueAbstraction> "),
					 GenerateVariable(value_abstraction_name_->This()), GenerateVariable(";")}));
			*value_abstraction_name_ = Variable_value_abstraction_name_(
				this, std::vector<VariableBase*>(
						  {GenerateVariable("value_abstraction__"),
						   GenerateVariable(value_abstraction_primary_name_->This())}));
			*value_abstraction_primary_name_ =
				Variable_value_abstraction_primary_name_(this, std::vector<VariableBase*>({}));
			*value_object_declaration_ = Variable_value_object_declaration_(
				this, std::vector<VariableBase*>(
						  {GenerateVariable("::deamer::type::SafeReserve<::deamer::language::type::"
											"definition::object::main::ValueObject> "),
						   GenerateVariable(value_rule_name_->This()), GenerateVariable(";")}));
			*value_object_name_ = Variable_value_object_name_(this, std::vector<VariableBase*>({}));
			*value_rule_name_ = Variable_value_rule_name_(
				this, std::vector<VariableBase*>({GenerateVariable("value_object__"),
												  GenerateVariable(value_object_name_->This())}));

			variables_.emplace_back(file_);
			variables_.emplace_back(header_guard_);
			variables_.emplace_back(language_full_name_);
			variables_.emplace_back(language_full_name_slash_);
			variables_.emplace_back(language_full_name_underscore_);
			variables_.emplace_back(left_angle_bracket_);
			variables_.emplace_back(left_bracket_);
			variables_.emplace_back(left_curly_bracket_);
			variables_.emplace_back(right_angle_bracket_);
			variables_.emplace_back(right_bracket_);
			variables_.emplace_back(right_curly_bracket_);
			variables_.emplace_back(unknown_reference_);
			variables_.emplace_back(unknown_reference_declaration_);
			variables_.emplace_back(value_abstraction_declaration_);
			variables_.emplace_back(value_abstraction_name_);
			variables_.emplace_back(value_abstraction_primary_name_);
			variables_.emplace_back(value_object_declaration_);
			variables_.emplace_back(value_object_name_);
			variables_.emplace_back(value_rule_name_);
		}

		virtual ~ValueHTemplate()
		{
			for (auto* variable : variables_to_delete)
			{
				delete variable;
			}

			variables_to_delete.clear();
		}

	public:
		// Default DST functions

		/*!	\fn GetOutput
		 *
		 *	\brief returns the output with the given the current state.
		 */
		std::string GetOutput()
		{
			return file_->Content()->GetValue();
		}

		/*!	\fn GetVariables
		 *
		 *	\brief Returns all top level variables known in this template.
		 */
		std::vector<VariableBase*> GetVariables()
		{
			return variables_;
		}

	public:
	};
}

#endif // DLDL_FILETEMPLATE_VALUEHTEMPLATE_h
